// Copyright (c) 2026 Jurjen Stellingwerff
// SPDX-License-Identifier: LGPL-3.0-or-later
//
//! loft#717 — the crash reporter's diagnostic must survive a pipeline.
//!
//! The reporter has always printed the last opcode, bytecode position and
//! function name, but only to stderr.  A package sweep that pipes stderr
//! through a filter discarded exactly that (`loft test` over 8 packages: one
//! SIGSEGV, and all that survived was the header line).  Every other thing a
//! build prints can be regenerated by running it again; a crash report cannot,
//! because the run that produced it is the run that will not repeat.
//!
//! So the guarantee under test is end-to-end and deliberately hostile: a real
//! fatal signal, with stderr sent to `/dev/null`, must still leave a readable
//! report on disk.  A unit test of the path-picking alone would pass while the
//! handler wrote nothing — the whole risk lives in whether a signal handler,
//! restricted to async-signal-safe calls, gets the bytes out at all.
//!
//! This lives in its own test binary because `crash_report::install` is
//! process-wide and resolves the destination ONCE: sharing a process with
//! another test that installs first would silently pin a different path.

// approved exemption: `fork` and the POSIX signal handler the crash reporter rides (unix-only by design) have no Windows equivalent; Windows substitute: none
#![cfg(unix)]

use loft::file_access as fa;
use std::path::PathBuf;

/// Fault a forked child for real, with `stderr` pointed at `/dev/null`, and
/// answer how the child died.
///
/// The child dereferences a null pointer rather than calling `raise`: the
/// handler is armed `SA_RESETHAND`, so it reports and then lets the default
/// action take the process — but only a FAULTING INSTRUCTION re-executes and
/// re-raises.  An explicit `raise` returns and the child walks on, which would
/// have tested a milder thing than the one #717 is about.
///
/// `install` runs in the PARENT, before the fork: resolving the report path
/// allocates, and after a fork only async-signal-safe calls are sound.  The
/// child therefore only faults — the handler that follows is `open`/`write`/
/// `close` and nothing else, which is precisely what it must be.
fn crash_a_child() -> libc::c_int {
    unsafe {
        let pid = libc::fork();
        assert!(pid >= 0, "fork failed");
        if pid == 0 {
            // Child: discard stderr entirely, the way the sweep in #717 did.
            let devnull = libc::open(c"/dev/null".as_ptr(), libc::O_WRONLY);
            if devnull >= 0 {
                libc::dup2(devnull, libc::STDERR_FILENO);
            }
            // A deliberate null write — `write_volatile` so it cannot be
            // optimised away into something that never faults.
            std::ptr::write_volatile(std::ptr::null_mut::<u8>(), 1);
            // Only reached if the fault did not kill us, which is itself a
            // failure — the parent distinguishes it by this exit code.
            libc::_exit(97);
        }
        let mut status: libc::c_int = 0;
        assert!(
            libc::waitpid(pid, &raw mut status, 0) == pid,
            "waitpid failed"
        );
        status
    }
}

#[test]
fn crash_diagnostic_survives_a_discarded_stderr() {
    let dir = std::env::temp_dir().join(format!("loft-crash-717-{}", std::process::id()));
    fa::create_dir_all(&dir).expect("scratch dir");
    let target: PathBuf = dir.join("report.txt");
    // SAFETY: this binary is single-threaded at this point (one #[test] per
    // process under nextest, and the fork below happens after this).
    unsafe {
        std::env::set_var("LOFT_CRASH_FILE", &target);
    }

    loft::crash_report::install("loft");
    assert_eq!(
        loft::crash_report::crash_file_path().as_deref(),
        Some(target.to_string_lossy().as_ref()),
        "install resolves the destination from LOFT_CRASH_FILE"
    );

    // A run that does not crash leaves nothing behind: the file is created by
    // the handler, not by arming it.
    assert!(
        !fa::exists(&target),
        "installing the handler must not create the report file"
    );

    // Publish a context so the report carries something worth recovering —
    // this is the opcode/pc/function that #717 lost.
    loft::crash_report::set_context(4321, 7, "OpGetRecord", 42, "sim_step");

    let status = crash_a_child();
    assert!(
        libc::WIFSIGNALED(status),
        "the child must still die of the signal — the handler reports, it does not swallow \
         (raw status {status})"
    );
    assert_eq!(
        libc::WTERMSIG(status),
        libc::SIGSEGV,
        "and it dies of the signal that was raised"
    );

    let report = fa::read_to_string(&target).unwrap_or_else(|e| {
        panic!(
            "no crash report at {} — the diagnostic was lost exactly as in #717: {e}",
            target.display()
        )
    });
    for want in [
        "loft crash",
        "SIGSEGV",
        "OpGetRecord",
        "4321",
        "sim_step",
        "42",
    ] {
        assert!(
            report.contains(want),
            "the report must name {want:?}, which is what makes a one-off crash actionable.\n\
             got:\n{report}"
        );
    }

    let _ = fa::remove_dir_all(&dir);
}
