// Copyright (c) 2026 Jurjen Stellingwerff
// SPDX-License-Identifier: LGPL-3.0-or-later

//! @PLN18 phase 01 ACCEPTANCE — the audience server ported onto the kernel
//! behaves **identically** to the original: one protocol scenario (seed /
//! erase / ignore / clear / select / snapshot / join-replay) drives BOTH
//! servers; the per-client transcripts must be equal.

use loft::file_access as fa;
use std::io::{Read, Write};
use std::net::TcpStream;
use std::path::PathBuf;
use std::process::{Child, Stdio};
use std::time::{Duration, Instant};

mod common;

/// VM-aware deadline: CI runners are slow and CONTENDED (parallel test
/// binaries + native-build storms) — scale every wait there so timing
/// reflects the machine, not the meaning.
/// Disk-backed scratch for test fixtures.  `std::env::temp_dir()` is a
/// RAM-backed tmpfs on dev boxes (small quota, shared across sessions), and
/// loft's cache-next-to-source rule would put every `--native` fixture's
/// binary cache there too — the disk-quota stall class.  `target/` lives on
/// disk and is cleaned with the build tree.
fn test_tmp() -> std::path::PathBuf {
    let dir = std::path::PathBuf::from(env!("CARGO_MANIFEST_DIR")).join("target/test-tmp");
    let _ = fa::create_dir_all(&dir);
    dir
}

fn vm_deadline(secs: u64) -> Instant {
    // Stretch the budget when the machine is shared — see `common::deadline_scale`.
    Instant::now() + Duration::from_secs(secs * common::deadline_scale())
}

fn root() -> PathBuf {
    PathBuf::from(env!("CARGO_MANIFEST_DIR"))
}

struct Guard(Option<Child>);
impl Drop for Guard {
    fn drop(&mut self) {
        if let Some(mut c) = self.0.take() {
            let _ = c.kill();
            let _ = c.wait();
        }
    }
}

// A minimal package context for the server scripts.  The original-port leg's
// `server.loft` does `use server;` — a REGISTRY package — which can only resolve
// inside a package whose manifest declares it.  We declare ONLY `server` (+ its
// transitive `web` dep), NOT the audience-demo's `graphics`, so the leg resolves
// offline from the installed registry without dragging in deps a box may lack.
// The kernel leg's `use engine_host;` is unaffected (it still comes from `--lib
// lib`; `engine_host` is not a declared dep here, so no shadowing).
//
// Pins must stay in sync with tools/audience-demo/loft.lock so the original-port
// transcript stays comparable to the kernel port.
const SERVER_MANIFEST: &str = "\
[package]
name = \"eh_aud_server_leg\"
version = \"0.0.0\"

[dependencies]
server = \"0.7.1\"
";

const SERVER_LOCK: &str = "\
# Auto-generated by loft — do not edit by hand.
schema_version = 1

[[package]]
name = \"web\"
version = \"0.4.2\"
url = \"https://github.com/loft-lang/loft-libs-net/releases/download/web-v0.4.2/web-0.4.2.tar.gz\"
sha256 = \"44d0469d0ecc3ca08006b80d4c507e8c2a4005c650e01fa59ca3a866da123e25\"
source = \"registry\"

[[package]]
name = \"server\"
version = \"0.7.1\"
url = \"https://github.com/loft-lang/loft-libs-net/releases/download/server-v0.7.1/server-0.7.1.tar.gz\"
sha256 = \"08bbdc7abcc1fc2e508de942592b3c2875d7aa06c5c6f456c74b20d65bcfd2db\"
source = \"registry\"
deps = [\"web\"]
";

fn spawn_server(script: &str) -> Guard {
    // Run from a temp PACKAGE dir (manifest + lock) — NOT a bare temp file.  The
    // bare-file copy used previously escaped any package context, so the original
    // leg's `use server;` (a registry package) could never resolve and that leg
    // only ever "passed" by being CI-skipped.  With a manifest declaring `server`,
    // it resolves offline from the installed registry and the leg actually runs.
    let src = fa::read_to_string(root().join(script)).expect("read fixture");
    let name = fa::file_name(script).unwrap();
    // Per-script pkg dir: the kernel + original legs run sequentially (the first
    // Guard drops/kills before the second spawns), but a per-script dir keeps each
    // leg's manifest/script fully isolated regardless of ordering.
    let pkg = test_tmp().join(format!("eh_aud_{}_{name}_pkg", std::process::id()));
    fa::create_dir_all(&pkg).expect("create pkg dir");
    fa::write(pkg.join("loft.toml"), SERVER_MANIFEST).expect("write manifest");
    fa::write(pkg.join("loft.lock"), SERVER_LOCK).expect("write lock");
    let tmp = pkg.join(format!("eh_aud_{}_{name}", std::process::id()));
    fa::write(&tmp, src).expect("write fixture copy");
    let child = loft::platform::process::harness_command(root().join("target/release/loft"))
        .env("LOFT_OFFLINE", "1") // hermetic: no registry fetches, installed-only
        .args(["--interpret", "--no-warnings", "--lib"])
        .arg(root().join("lib"))
        .arg(&tmp)
        .current_dir(&pkg)
        // Captured, not nulled: when the server dies at startup on a CI
        // box, ws_connect's panic prints these (the only forensics there).
        .stdout(Stdio::from(fa::create(server_log_path("out")).unwrap()))
        .stderr(Stdio::from(fa::create(server_log_path("err")).unwrap()))
        .spawn()
        .expect("spawn server");
    Guard(Some(child))
}

/// Whether the `server` registry package resolves OFFLINE here — true on a box
/// where `loft install` has fetched it, false on a bare box.  Compiles a tiny
/// probe that references a `server::` type so resolution is actually forced
/// (a bare `use server;` with no reference could be elided), and reports whether
/// it built.  Used to run the original-port leg only where `server` exists.
fn server_available() -> bool {
    let pkg = test_tmp().join(format!("eh_aud_{}_srvprobe", std::process::id()));
    if fa::create_dir_all(&pkg).is_err() {
        return false;
    }
    if fa::write(pkg.join("loft.toml"), SERVER_MANIFEST).is_err()
        || fa::write(pkg.join("loft.lock"), SERVER_LOCK).is_err()
    {
        return false;
    }
    let probe = pkg.join("srvprobe.loft");
    let body = "use server::*;\nfn _p(s: server::Server) -> server::Server { s }\nfn main() {}\n";
    if fa::write(&probe, body).is_err() {
        return false;
    }
    loft::platform::process::harness_command(root().join("target/release/loft"))
        .env("LOFT_OFFLINE", "1")
        .args(["--interpret", "--no-warnings"])
        .arg(&probe)
        .current_dir(&pkg)
        .output()
        .map(|o| o.status.success())
        .unwrap_or(false)
}

fn server_log_path(ext: &str) -> std::path::PathBuf {
    test_tmp().join(format!("eh_aud_srv_{}.{ext}", std::process::id()))
}

fn server_logs() -> String {
    let read = |ext: &str| fa::read_to_string(server_log_path(ext)).unwrap_or_default();
    format!(
        "server stdout:\n{}\nserver stderr:\n{}",
        read("out"),
        read("err")
    )
}

fn ws_connect(port: u16) -> TcpStream {
    let deadline = vm_deadline(15);
    let stream = loop {
        match TcpStream::connect(("127.0.0.1", port)) {
            Ok(s) => break s,
            Err(e) => assert!(
                Instant::now() < deadline,
                "server never listened (last connect error: {e})\n{}",
                server_logs()
            ),
        }
        std::thread::sleep(Duration::from_millis(100));
    };
    stream
        .set_read_timeout(Some(Duration::from_secs(5)))
        .unwrap();
    let req = "GET /ws HTTP/1.1\r\nHost: x\r\nUpgrade: websocket\r\nConnection: Upgrade\r\n\
               Sec-WebSocket-Key: dGhlIHNhbXBsZSBub25jZQ==\r\nSec-WebSocket-Version: 13\r\n\r\n";
    (&stream).write_all(req.as_bytes()).unwrap();
    let mut head = Vec::new();
    let mut b = [0u8; 1];
    while !head.ends_with(b"\r\n\r\n") {
        (&stream).read_exact(&mut b).unwrap();
        head.push(b[0]);
    }
    assert!(String::from_utf8_lossy(&head).contains("101"));
    stream
}

fn ws_send(stream: &TcpStream, text: &str) {
    let mask = [9u8, 8, 7, 6];
    let bytes = text.as_bytes();
    let mut frame = vec![0x81u8, 0x80 | bytes.len() as u8];
    frame.extend_from_slice(&mask);
    frame.extend(bytes.iter().enumerate().map(|(i, b)| b ^ mask[i % 4]));
    let mut s = stream;
    s.write_all(&frame).unwrap();
}

fn ws_recv(stream: &TcpStream) -> String {
    let mut s = stream;
    let mut hdr = [0u8; 2];
    s.read_exact(&mut hdr).unwrap();
    let len = match hdr[1] & 0x7F {
        126 => {
            let mut b = [0u8; 2];
            s.read_exact(&mut b).unwrap();
            u16::from_be_bytes(b) as usize
        }
        n => n as usize,
    };
    let mut payload = vec![0u8; len];
    s.read_exact(&mut payload).unwrap();
    String::from_utf8(payload).unwrap()
}

/// Drive the protocol scenario; return (client A transcript, client B transcript).
fn scenario(port: u16) -> (Vec<String>, Vec<String>) {
    let mut a_log = Vec::new();
    let mut b_log = Vec::new();

    let a = ws_connect(port);
    std::thread::sleep(Duration::from_millis(200)); // connect handling settles

    // 1. A seeds (2,3) color 5 → delta to A (sender confirmation).
    ws_send(&a, "1:2,3,5");
    a_log.push(ws_recv(&a));

    // 2. B joins → replay of the one live cell.
    let b = ws_connect(port);
    b_log.push(ws_recv(&b));

    // 3. Other-color tap on the taken cell: IGNORED (no frames) — covered by
    //    transcript order: the next frame anyone sees is step 4's erase.
    ws_send(&a, "1:2,3,7");
    std::thread::sleep(Duration::from_millis(150));

    // 4. Own-color tap → erase, broadcast to both.
    ws_send(&a, "1:2,3,5");
    a_log.push(ws_recv(&a));
    b_log.push(ws_recv(&b));

    // 5. Seed (4,4) c2, then explicit clear — both broadcast.
    ws_send(&a, "1:4,4,2");
    a_log.push(ws_recv(&a));
    b_log.push(ws_recv(&b));
    ws_send(&a, "2:4,4");
    a_log.push(ws_recv(&a));
    b_log.push(ws_recv(&b));

    // 6. A seeds (7,7) c3 (sets A's last-active), then selects a colour →
    //    active hint at A's last paint.
    ws_send(&a, "1:7,7,3");
    a_log.push(ws_recv(&a));
    b_log.push(ws_recv(&b));
    ws_send(&a, "3:6");
    a_log.push(ws_recv(&a));
    b_log.push(ws_recv(&b));

    // 7. B requests a snapshot → replay of the live world ((7,7) only).
    ws_send(&b, "6:");
    b_log.push(ws_recv(&b));

    (a_log, b_log)
}

#[test]
fn kernel_port_matches_original() {
    if !fa::exists(root().join("target/release/loft")) {
        eprintln!("skipping: release loft not built");
        return;
    }
    let expected_a = vec![
        "4:2,3,5".to_string(), // seed confirmed
        "4:2,3,0".to_string(), // own-color erase
        "4:4,4,2".to_string(), // seed
        "4:4,4,0".to_string(), // clear
        "4:7,7,3".to_string(), // seed
        "5:7,7".to_string(),   // active at last paint
    ];
    let expected_b = vec![
        "4:2,3,5".to_string(), // join replay
        "4:2,3,0".to_string(),
        "4:4,4,2".to_string(),
        "4:4,4,0".to_string(),
        "4:7,7,3".to_string(),
        "5:7,7".to_string(),
        "4:7,7,3".to_string(), // snapshot replay
    ];

    // The kernel port.
    let (ka, kb) = {
        let _g = spawn_server("tools/audience-demo/server_kernel.loft");
        scenario(18083)
    };
    assert_eq!(ka, expected_a, "kernel port, client A");
    assert_eq!(kb, expected_b, "kernel port, client B");

    // The original (lib/server pump).  `server` is a REGISTRY package (no in-repo
    // lib/server); spawn_server now runs it OFFLINE from a pinned manifest+lock, so
    // the old "network-mutated registry" race that forced a blanket CI skip is gone
    // — there are no network fetches and the version is pinned.  The one remaining
    // precondition is that `server` is installed locally (a dev box where the deps
    // were `loft install`ed — and CI too, if it installs them).  Probe and skip
    // gracefully when it's absent, rather than fail a box that simply lacks it.
    if !server_available() {
        eprintln!(
            "SKIP original-port leg: `server` package not resolvable offline (not installed)"
        );
        return;
    }
    std::thread::sleep(Duration::from_millis(300)); // port release
    let (oa, ob) = {
        let _g = spawn_server("tools/audience-demo/server.loft");
        scenario(18083)
    };
    assert_eq!(oa, expected_a, "original, client A");
    assert_eq!(ob, expected_b, "original, client B");

    // The differential acceptance: transcripts identical across servers.
    assert_eq!(ka, oa, "A transcripts identical across servers");
    assert_eq!(kb, ob, "B transcripts identical across servers");
}
