// Copyright (c) 2026 Jurjen Stellingwerff
// SPDX-License-Identifier: LGPL-3.0-or-later

//! loft#968 — `use <pkg>` resolves a registry package the manifest never declared.
//!
//! The resolution itself stays: a qualified `lib::fn()` auto-loads, and a self-healing
//! `loft.lock` is a convenience worth keeping. The silence was the defect. Nothing in a
//! project distinguished *"we depend on this"* from *"this happens to be installed on the
//! box that built it"* — measured on a 33 000-line consumer where deleting the
//! `[dependencies]` line, and then the `[[package]]` block from `loft.lock` too, left all
//! 18 tests passing. The negative gate that phase wanted (*drop the dependency and the
//! tests must fail to compile*) could not be written at all.
//!
//! Hermetic: `LOFT_HOME` points at a per-test directory with a hand-built package in its
//! registry cache, and `LOFT_OFFLINE=1` keeps resolution off the network. So these
//! measure resolution, not connectivity, and they cannot touch the developer's own cache.

#![cfg(feature = "registry")]

use loft::file_access as fa;
use std::path::{Path, PathBuf};
use std::process::Command;

fn loft_bin() -> PathBuf {
    PathBuf::from(env!("CARGO_BIN_EXE_loft"))
}

fn write(path: &Path, body: &str) {
    fa::create_dir_all(path.parent().unwrap()).expect("mkdir");
    fa::write(path, body).expect("write");
}

/// A project that `use`s `probepkg`, with `probepkg` already extracted in a private
/// registry cache and named by `loft.lock` — the exact end state the report describes,
/// since it is `loft` itself that writes the lock entry.  `manifest` decides whether the
/// project DECLARES the dependency; that is the axis under test.
///
/// Returns (stdout+stderr, exit code).
fn run_consumer(tag: &str, manifest: &str, with_lock: bool) -> (String, i32) {
    let base = std::env::temp_dir().join(format!("loft_968_{tag}_{}", std::process::id()));
    let _ = fa::remove_dir_all(&base);
    let home = base.join("home");
    let proj = base.join("proj");

    let pkg = home.join(".loft/registry/probepkg-0.1.0");
    write(
        &pkg.join("loft.toml"),
        "[package]\nname = \"probepkg\"\nversion = \"0.1.0\"\n\n[library]\n\
         entry = \"src/probepkg.loft\"\n",
    );
    write(
        &pkg.join("src/probepkg.loft"),
        "pub fn probe_answer() -> integer { 41 }\n",
    );

    write(&proj.join("loft.toml"), manifest);
    if with_lock {
        write(
            &proj.join("loft.lock"),
            "# Auto-generated by loft — do not edit by hand.\nschema_version = 1\n\n\
             [[package]]\nname = \"probepkg\"\nversion = \"0.1.0\"\n\
             url = \"http://localhost/probepkg-0.1.0.tar.gz\"\n\
             sha256 = \"0000000000000000000000000000000000000000000000000000000000000000\"\n\
             source = \"registry\"\n",
        );
    }
    write(
        &proj.join("consumer.loft"),
        "use probepkg::*;\n\nfn main() {\n  println(\"answer={probe_answer()}\");\n}\n",
    );

    let out = Command::new(loft_bin())
        .args(["--interpret", "consumer.loft"])
        .env("LOFT_HOME", &home)
        .env("HOME", &home)
        .env("USERPROFILE", &home)
        .env("LOFT_OFFLINE", "1")
        .env("LOFT_TIMEOUT", "90")
        .current_dir(&proj)
        .output()
        .expect("spawn loft");
    let all = format!(
        "{}{}",
        String::from_utf8_lossy(&out.stdout),
        String::from_utf8_lossy(&out.stderr)
    );
    let code = out.status.code().unwrap_or(-1);
    let _ = fa::remove_dir_all(&base);
    (all, code)
}

/// The reported case: the manifest declares nothing, the package resolves anyway.
/// Both halves matter — it must still RUN (the resolution is deliberate) and it must say
/// so (the silence is what could not be gated).
#[test]
fn an_undeclared_registry_package_resolves_and_says_so() {
    let (all, code) = run_consumer(
        "undeclared",
        "[package]\nname = \"undeclared_consumer\"\nversion = \"0.1.0\"\n",
        true,
    );
    assert_eq!(code, 0, "the program must still run\n{all}");
    assert!(all.contains("answer=41"), "…and answer correctly\n{all}");
    assert!(
        all.contains("advice[undeclared-dependency]"),
        "an undeclared registry package must be reported\n{all}"
    );
    assert!(
        all.contains("probepkg"),
        "the advice must name the package\n{all}"
    );
    // Once per `use`, not once per parse: the diagnostic is emitted from a resolution
    // path both parses walk, and a doubled advice reads as two separate findings.
    assert_eq!(
        all.matches("advice[undeclared-dependency]").count(),
        1,
        "one `use` should speak once\n{all}"
    );
}

/// The control, and the assertion that keeps the advice worth reading: a project that
/// DOES declare the package hears nothing.  Same package, same lock, same resolution
/// path — only the `[dependencies]` line differs, which is the whole claim.
#[test]
fn a_declared_dependency_is_silent() {
    let (all, code) = run_consumer(
        "declared",
        "[package]\nname = \"declared_consumer\"\nversion = \"0.1.0\"\n\n\
         [dependencies]\nprobepkg = \"^0.1\"\n",
        true,
    );
    assert_eq!(code, 0, "the program must still run\n{all}");
    assert!(all.contains("answer=41"), "…and answer correctly\n{all}");
    assert!(
        !all.contains("undeclared-dependency"),
        "a declared dependency has nothing to report\n{all}"
    );
}

/// A single-file script has no manifest to declare INTO, and running one against an
/// installed package is the whole point of auto-resolution (the `pip install` story).
/// Advice there would fire where there is nothing to fix, which is how a diagnostic
/// teaches people to skip the ones that matter.
#[test]
fn a_script_with_no_manifest_hears_nothing() {
    let base = std::env::temp_dir().join(format!("loft_968_nomanifest_{}", std::process::id()));
    let _ = fa::remove_dir_all(&base);
    let home = base.join("home");
    let pkg = home.join(".loft/registry/probepkg-0.1.0");
    write(
        &pkg.join("loft.toml"),
        "[package]\nname = \"probepkg\"\nversion = \"0.1.0\"\n\n[library]\n\
         entry = \"src/probepkg.loft\"\n",
    );
    write(
        &pkg.join("src/probepkg.loft"),
        "pub fn probe_answer() -> integer { 41 }\n",
    );
    let proj = base.join("scriptdir");
    write(
        &proj.join("loft.lock"),
        "# Auto-generated by loft — do not edit by hand.\nschema_version = 1\n\n\
         [[package]]\nname = \"probepkg\"\nversion = \"0.1.0\"\n\
         url = \"http://localhost/probepkg-0.1.0.tar.gz\"\n\
         sha256 = \"0000000000000000000000000000000000000000000000000000000000000000\"\n\
         source = \"registry\"\n",
    );
    write(
        &proj.join("script.loft"),
        "use probepkg::*;\n\nfn main() {\n  println(\"answer={probe_answer()}\");\n}\n",
    );

    let out = Command::new(loft_bin())
        .args(["--interpret", "script.loft"])
        .env("LOFT_HOME", &home)
        .env("HOME", &home)
        .env("USERPROFILE", &home)
        .env("LOFT_OFFLINE", "1")
        .env("LOFT_TIMEOUT", "90")
        .current_dir(&proj)
        .output()
        .expect("spawn loft");
    let all = format!(
        "{}{}",
        String::from_utf8_lossy(&out.stdout),
        String::from_utf8_lossy(&out.stderr)
    );
    let _ = fa::remove_dir_all(&base);
    assert!(all.contains("answer=41"), "the script must run\n{all}");
    assert!(
        !all.contains("undeclared-dependency"),
        "there is no manifest to declare into\n{all}"
    );
}

/// The off-switch, verified by its EFFECT rather than by being set.
#[test]
fn the_off_switch_silences_it() {
    let base = std::env::temp_dir().join(format!("loft_968_off_{}", std::process::id()));
    let _ = fa::remove_dir_all(&base);
    let home = base.join("home");
    let proj = base.join("proj");
    let pkg = home.join(".loft/registry/probepkg-0.1.0");
    write(
        &pkg.join("loft.toml"),
        "[package]\nname = \"probepkg\"\nversion = \"0.1.0\"\n\n[library]\n\
         entry = \"src/probepkg.loft\"\n",
    );
    write(
        &pkg.join("src/probepkg.loft"),
        "pub fn probe_answer() -> integer { 41 }\n",
    );
    write(
        &proj.join("loft.toml"),
        "[package]\nname = \"c\"\nversion = \"0.1.0\"\n",
    );
    write(
        &proj.join("loft.lock"),
        "# Auto-generated by loft — do not edit by hand.\nschema_version = 1\n\n\
         [[package]]\nname = \"probepkg\"\nversion = \"0.1.0\"\n\
         url = \"http://localhost/probepkg-0.1.0.tar.gz\"\n\
         sha256 = \"0000000000000000000000000000000000000000000000000000000000000000\"\n\
         source = \"registry\"\n",
    );
    write(
        &proj.join("consumer.loft"),
        "use probepkg::*;\n\nfn main() {\n  println(\"answer={probe_answer()}\");\n}\n",
    );
    let run = |off: bool| {
        let mut cmd = Command::new(loft_bin());
        cmd.args(["--interpret", "consumer.loft"])
            .env("LOFT_HOME", &home)
            .env("HOME", &home)
            .env("USERPROFILE", &home)
            .env("LOFT_OFFLINE", "1")
            .env("LOFT_TIMEOUT", "90")
            .current_dir(&proj);
        if off {
            cmd.env("LOFT_NO_UNDECLARED_DEP", "1");
        }
        let out = cmd.output().expect("spawn loft");
        format!(
            "{}{}",
            String::from_utf8_lossy(&out.stdout),
            String::from_utf8_lossy(&out.stderr)
        )
    };
    // The armed run first, so a silent OFF run cannot pass through a fixture that
    // never produced the advice in the first place.
    let armed = run(false);
    let silenced = run(true);
    let _ = fa::remove_dir_all(&base);
    assert!(
        armed.contains("undeclared-dependency"),
        "the fixture must produce the advice before the switch can be shown to remove \
         it\n{armed}"
    );
    assert!(
        !silenced.contains("undeclared-dependency"),
        "LOFT_NO_UNDECLARED_DEP must silence it\n{silenced}"
    );
    assert!(
        silenced.contains("answer=41"),
        "and must not change what the program does\n{silenced}"
    );
}
