// Copyright (c) 2026 Jurjen Stellingwerff
// SPDX-License-Identifier: LGPL-3.0-or-later

//! Cross-mode test harness for plan-14 tuple validation.
//!
//! Compiles and runs a loft snippet under both the **interpreter**
//! (`--interpret`) and the **`--native`** Rust-codegen pipeline,
//! captures both stdouts, and asserts they are byte-identical.  A
//! divergence is a recorded failure even if both modes individually
//! exit successfully.
//!
//! The cross-mode equivalence is the contract: a tuple cell that
//! passes interp but produces different output (or no output) under
//! `--native` is the historical pattern behind silent-corruption
//! P-issues (P200 / P203 / P205).  Catching that pattern at test
//! time is the whole point of this harness.
//!
//! See `doc/claude/plans/14-tuple-validation/00-matrix.md` for the
//! design.

use loft::file_access as fa;
use std::path::PathBuf;
use std::process::Command;

fn loft_bin() -> PathBuf {
    PathBuf::from(env!("CARGO_BIN_EXE_loft"))
}

fn workspace_root() -> PathBuf {
    PathBuf::from(env!("CARGO_MANIFEST_DIR"))
}

/// Outcome of one mode (interpreter or native).
struct ModeRun {
    stdout: String,
    stderr: String,
    success: bool,
    exit_code: Option<i32>,
}

fn run_mode(mode_flag: &str, snippet_path: &PathBuf) -> ModeRun {
    run_mode_env(mode_flag, snippet_path, &[])
}

fn run_mode_env(mode_flag: &str, snippet_path: &PathBuf, env: &[(&str, &str)]) -> ModeRun {
    let mut cmd = Command::new(loft_bin());
    cmd.arg(mode_flag)
        .arg(snippet_path)
        .current_dir(workspace_root());
    for (k, v) in env {
        cmd.env(k, v);
    }
    let out = cmd
        .output()
        .unwrap_or_else(|e| panic!("failed to spawn loft binary in {mode_flag} mode: {e}"));
    ModeRun {
        stdout: String::from_utf8_lossy(&out.stdout).into_owned(),
        stderr: String::from_utf8_lossy(&out.stderr).into_owned(),
        success: out.status.success(),
        exit_code: out.status.code(),
    }
}

/// Normalise stdout for byte-identical comparison.
///
/// - Trim trailing whitespace on every line.
/// - Normalise CRLF → LF (Windows native binaries may emit CRLF).
/// - Collapse a trailing run of blank lines to a single newline.
///
/// Snippets that depend on exact whitespace inside a line are still
/// compared byte-for-byte for that line; only line endings and the
/// final-blank-lines tail are normalised.
fn normalise_stdout(s: &str) -> String {
    let lf = s.replace("\r\n", "\n");
    let mut lines: Vec<&str> = lf.lines().map(str::trim_end).collect();
    while lines.last().is_some_and(|l| l.is_empty()) {
        lines.pop();
    }
    let mut out = lines.join("\n");
    if !out.is_empty() {
        out.push('\n');
    }
    out
}

/// Run `body` under interp + native, assert success in both, assert
/// stdout-equality between modes.
///
/// `body` is the **complete** loft source for the test — it must
/// declare `fn test() { … }` (the entry point) and any helper fns
/// the test needs (loft does not allow nested fn definitions).  The
/// harness appends `fn main() { test(); }` so the snippet is a
/// runnable program.
///
/// Snippets should `print(...)` their observations and `assert(...)`
/// their invariants; both modes will produce identical stdout when
/// the assertion holds.
pub fn run_cross_mode(test_name: &str, body: &str) {
    let source = format!(
        "// auto-generated by tests/common/cross_mode.rs for {test_name}\n\
         {body}\n\
         fn main() {{ test(); }}\n"
    );

    let snippet_path = std::env::temp_dir().join(format!("loft_xmode_{test_name}.loft"));
    fa::write(&snippet_path, &source)
        .unwrap_or_else(|e| panic!("write snippet for {test_name}: {e}"));

    let interp = run_mode("--interpret", &snippet_path);
    let native = run_mode("--native", &snippet_path);

    let _ = fa::remove_file(&snippet_path);

    let interp_stdout = normalise_stdout(&interp.stdout);
    let native_stdout = normalise_stdout(&native.stdout);

    if !interp.success {
        panic!(
            "{test_name}: interp run failed (exit {:?})\n\
             ---- stdout ----\n{}\
             ---- stderr ----\n{}",
            interp.exit_code, interp.stdout, interp.stderr,
        );
    }
    if !native.success {
        panic!(
            "{test_name}: native run failed (exit {:?})\n\
             ---- stdout ----\n{}\
             ---- stderr ----\n{}",
            native.exit_code, native.stdout, native.stderr,
        );
    }
    if interp_stdout != native_stdout {
        panic!(
            "{test_name}: interp/native stdout divergence\n\
             ---- interp ({} bytes) ----\n{interp_stdout}\
             ---- native ({} bytes) ----\n{native_stdout}",
            interp_stdout.len(),
            native_stdout.len(),
        );
    }
}

/// Like [`run_cross_mode`] (byte-identical interp/native stdout) but ALSO asserts
/// both backends' stdout contains `expected` — so the cell is non-vacuous (two
/// wrong-but-identical outputs can't pass). Used by @PLN105's deliver parity gate.
pub fn run_cross_mode_expect(test_name: &str, body: &str, expected: &str) {
    let source = format!(
        "// auto-generated by tests/common/cross_mode.rs for {test_name}\n\
         {body}\n\
         fn main() {{ test(); }}\n"
    );
    let snippet_path = std::env::temp_dir().join(format!("loft_xmode_{test_name}.loft"));
    fa::write(&snippet_path, &source)
        .unwrap_or_else(|e| panic!("write snippet for {test_name}: {e}"));
    let interp = run_mode("--interpret", &snippet_path);
    let native = run_mode("--native", &snippet_path);
    let _ = fa::remove_file(&snippet_path);

    for (label, run) in [("interp", &interp), ("native", &native)] {
        assert!(
            run.success,
            "{test_name}: {label} run failed (exit {:?})\n---- stdout ----\n{}---- stderr ----\n{}",
            run.exit_code, run.stdout, run.stderr,
        );
        assert!(
            run.stdout.contains(expected),
            "{test_name}: {label} stdout missing expected {expected:?}\n---- stdout ----\n{}",
            run.stdout,
        );
    }
    let (i, n) = (
        normalise_stdout(&interp.stdout),
        normalise_stdout(&native.stdout),
    );
    assert_eq!(i, n, "{test_name}: interp/native stdout divergence");
}

/// #318/C75: run `body` under interp + native and assert BOTH backends
/// reject it at compile time with `expected` on stderr.  Locks a
/// closed-by-decision rejection into the cross-backend matrix the same
/// way `run_cross_mode` locks working behaviour.
pub fn run_cross_mode_rejected(test_name: &str, body: &str, expected: &str) {
    let source = format!(
        "// auto-generated by tests/common/cross_mode.rs for {test_name}\n\
         {body}\n\
         fn main() {{ test(); }}\n"
    );
    let snippet_path = std::env::temp_dir().join(format!("loft_xmode_{test_name}.loft"));
    fa::write(&snippet_path, &source)
        .unwrap_or_else(|e| panic!("write snippet for {test_name}: {e}"));
    let interp = run_mode("--interpret", &snippet_path);
    let native = run_mode("--native", &snippet_path);
    let _ = fa::remove_file(&snippet_path);
    for (label, run) in [("interp", &interp), ("native", &native)] {
        assert!(
            !run.success,
            "{test_name}: {label} unexpectedly succeeded\n---- stdout ----\n{}",
            run.stdout,
        );
        assert!(
            run.stderr.contains(expected),
            "{test_name}: {label} failed without the expected rejection\n\
             expected substring: {expected}\n---- stderr ----\n{}",
            run.stderr,
        );
    }
}

/// Run `body` under interp + native and assert NEITHER backend leaks a
/// store at program exit.
///
/// Both backends report leaks the same way — a `Warning: N stores not
/// freed at program exit: …` line on stderr.  The interpreter prints it
/// unconditionally; the native binary prints it only when
/// `LOFT_NATIVE_LEAK_CHECK` is set (so normal native runs stay quiet),
/// which this harness sets for the native run.  A leak on either backend
/// is a recorded failure.
///
/// This is the cross-backend counterpart to the in-process
/// `collect_store_leaks` checks in `tests/leak.rs`: those guard the
/// interpreter cheaply; this guards `--native` too, where leaks have
/// historically gone undetected (the generated binary had no exit-time
/// leak check before @P297).
pub fn run_cross_mode_leak_free(test_name: &str, body: &str) {
    let source = format!(
        "// auto-generated by tests/common/cross_mode.rs for {test_name}\n\
         {body}\n\
         fn main() {{ test(); }}\n"
    );

    let snippet_path = std::env::temp_dir().join(format!("loft_leak_{test_name}.loft"));
    fa::write(&snippet_path, &source)
        .unwrap_or_else(|e| panic!("write snippet for {test_name}: {e}"));

    let interp = run_mode("--interpret", &snippet_path);
    let native = run_mode_env(
        "--native",
        &snippet_path,
        &[("LOFT_NATIVE_LEAK_CHECK", "1")],
    );

    let _ = fa::remove_file(&snippet_path);

    for (mode, run) in [("interp", &interp), ("native", &native)] {
        assert!(
            run.success,
            "{test_name}: {mode} run failed (exit {:?})\n\
             ---- stdout ----\n{}\
             ---- stderr ----\n{}",
            run.exit_code, run.stdout, run.stderr,
        );
        assert!(
            !run.stderr.contains("stores not freed"),
            "{test_name}: {mode} leaked stores\n---- stderr ----\n{}",
            run.stderr,
        );
    }
}

/// Define a test that runs `body` under both interp and `--native`
/// and asserts byte-identical stdout.
///
/// **Runs by default** (@PLN114).  These cells were `#[ignore]`d as "too heavy for
/// the default `cargo test` path" — each shells out to the `loft` binary twice and
/// `--native` invokes `rustc`.  Measured, the whole 201-cell set takes ~10 seconds,
/// so the cost was never the issue; the silence was.  Two SIGSEGVs, a silent `+1`
/// corruption of every narrow tuple element, a 3.4x memory overhead and a
/// cross-backend par-worker corruption all sat behind that `#[ignore]` until the set
/// was run by hand.  A guarantee nothing executes is not a guarantee.
///
/// Run one cell:
///
/// ```bash
/// cargo test --release --test tuple_matrix e1_d1_int_int_local
/// ```
///
/// ```ignore
/// cross_mode!(my_cell, "
///     t = (3, 7);
///     print(\"{t.0},{t.1}\\n\");
///     assert(t.0 == 3 && t.1 == 7, \"my_cell\");
/// ");
/// ```
#[macro_export]
macro_rules! cross_mode {
    ($name:ident, $body:expr) => {
        #[test]
        fn $name() {
            $crate::common::cross_mode::run_cross_mode(stringify!($name), $body);
        }
    };
}
