#!/usr/bin/env bash
# Copyright (c) 2026 Jurjen Stellingwerff
# SPDX-License-Identifier: LGPL-3.0-or-later
#
# deploy-library-ci — give every loft-lang/loft-libs-* repo the SAME three workflow
# stubs, each a thin caller of a reusable that lives elsewhere:
#
#   library-ci.yml   → loft-lang/loft   (the build gate; packages listed per repo)
#   fpm-apply.yml    → loft-lang/.github (label `fixed-pending-merge` on a Fixes push)
#                      …and the LABEL itself, which is a repo setting rather than a file
#   fpm-strip.yml    → loft-lang/.github (strip it again when the issue closes)
#
# Each repo's packages are computed from its actual package dirs (a dir with a
# loft.toml), so the caller stays correct even as packages are added.
#
# WHY: the per-repo copies had drifted — a stale `jjstwerff/loft` checkout URL in most,
# an incomplete package matrix in some, and NO CI at all in loft-libs-docs.  Centralising
# the build logic fixes all of that in one place.
#
# The lifecycle stubs were the half that stayed un-unified: only loft-libs-graphics
# carried them, so in the other seven repos a `Fixes #NNN` push labelled nothing and
# the tracker showed a fixed bug as untouched — the exact state the automation exists
# to prevent, and invisible precisely because nothing fails when a label is missing.
# They are listed in LIBRARY_CHECKLIST.md § Structure & packaging as required.
#
# PREREQUISITE: the reusable workflow must already be on loft-lang/loft@main (the callers
# reference it at @main).  Run this AFTER that lands.
#
# Pushes ONE branch per repo; it does NOT open PRs — landing is the maintainer's call.
#
# Usage:
#   scripts/deploy-library-ci.sh [--branch <name>] [--dry-run]
set -euo pipefail

ORG=loft-lang
BRANCH=unify-library-ci
DRY=0
while [ $# -gt 0 ]; do
  case "$1" in
    --branch) BRANCH="$2"; shift 2 ;;
    --dry-run) DRY=1; shift ;;
    *) echo "unknown arg: $1" >&2; exit 2 ;;
  esac
done

NAME=$(git config user.name  || echo "loft maintainer")
EMAIL=$(git config user.email || echo "maintainer@loft-lang.org")
tmp=$(mktemp -d -t deploy-library-ci.XXXXXX)
trap 'rm -rf "$tmp"' EXIT

repos=$(gh api "orgs/$ORG/repos?per_page=100" --jq '.[].name' | grep '^loft-libs-' || true)
[ -n "$repos" ] || { echo "no loft-libs-* repos found (is gh authenticated?)" >&2; exit 1; }

for r in $repos; do
  git clone --quiet --depth 1 "https://github.com/$ORG/$r.git" "$tmp/$r"
  (
    cd "$tmp/$r"
    pkgs=$(for d in */; do [ -f "${d}loft.toml" ] && basename "$d"; done | sort)
    if [ -z "$pkgs" ]; then echo "  $r: no packages — skip"; exit 0; fi

    # The label the fpm-apply workflow applies is a REPO SETTING, not a file, so
    # pushing the workflow never creates it.  Every loft-libs-* repo got the
    # workflow here and none got the label, and the failure waited until the first
    # PR that actually carried a `Fixes #N`: `'fixed-pending-merge' not found`,
    # exit 1, on a job that has nothing to do with the change under review.
    #
    # It goes BEFORE the "already unified" early-out below on purpose — that
    # early-out is why this never self-healed, since a repo whose workflows are
    # current skips every step after it.  `gh label create` is idempotent with
    # `--force`, so re-running costs one API call and fixes a missing label.
    if [ "$DRY" = 0 ]; then
      gh label create fixed-pending-merge --repo "$ORG/$r" --force \
        --color 2da44e \
        --description "Fixed/implemented on the branch; only merge remains. Auto-closes on merge." \
        > /dev/null 2>&1 || echo "  $r: WARNING could not ensure the fixed-pending-merge label"
    fi
    json=$(printf '%s\n' $pkgs | python3 -c 'import sys,json; print(json.dumps([l.strip() for l in sys.stdin if l.strip()]))')

    mkdir -p .github/workflows
    cat > .github/workflows/library-ci.yml <<YAML
# Generated by loft-lang/loft scripts/deploy-library-ci.sh — the UNIFIED library CI.
# The build logic and the loft checkout URL live in the reusable workflow; this file
# only lists this repo's packages and the token scope it lends.  To change the gate,
# edit the reusable in loft-lang/loft, not these copies.
name: library-ci
on:
  push:
    branches: [main]
  pull_request:
jobs:
  ci:
    uses: $ORG/loft/.github/workflows/library-ci-reusable.yml@main
    # A called workflow CANNOT elevate: its token is whatever the caller lends it, and
    # asking for more is a startup failure with no job, no annotation and no log —
    # only "This run likely failed because of a workflow file issue".  These repos
    # default to `read`, which is `contents` + `packages` and nothing else, so the
    # `unreleased work` job's PR listing has to be granted HERE (loft#1492).
    permissions:
      contents: read
      pull-requests: read
    with:
      packages: '$json'
YAML

    # The org lifecycle stubs.  Identical in every repo — no per-repo substitution —
    # so they are written verbatim rather than generated.
    cat > .github/workflows/fpm-apply.yml <<'YAML'
# Generated by loft-lang/loft scripts/deploy-library-ci.sh — do not edit here.
name: fixed-pending-merge (apply)
on:
  push:
    branches-ignore: [main]
permissions:
  issues: write
jobs:
  apply:
    uses: loft-lang/.github/.github/workflows/apply-fixed-pending-merge.yml@main
YAML
    cat > .github/workflows/fpm-strip.yml <<'YAML'
# Generated by loft-lang/loft scripts/deploy-library-ci.sh — do not edit here.
name: fixed-pending-merge (strip)
on:
  issues:
    types: [closed]
permissions:
  issues: write
jobs:
  strip:
    uses: loft-lang/.github/.github/workflows/strip-fixed-pending-merge.yml@main
YAML

    # Stage explicitly so a repo that has NONE of these is still detected as changed.
    git add .github/workflows/library-ci.yml \
            .github/workflows/fpm-apply.yml \
            .github/workflows/fpm-strip.yml
    if git diff --cached --quiet; then
      echo "  $r: already unified — skip"; exit 0
    fi
    if [ "$DRY" = 1 ]; then
      echo "  $r: WOULD push $BRANCH (packages $json)"; exit 0
    fi
    git config user.name  "$NAME"
    git config user.email "$EMAIL"
    git checkout -q -b "$BRANCH"
    git commit -q -m "ci: adopt the unified reusable workflows (packages: $json)"
    git push -q -u origin "$BRANCH"
    echo "  $r: pushed $BRANCH (packages $json) — open a PR to land"
  )
done
echo "done. Open a PR per repo (or: gh pr create -R $ORG/<repo> -H $BRANCH)."
