#!/usr/bin/env python3
# Copyright (c) 2026 Jurjen Stellingwerff
# SPDX-License-Identifier: LGPL-3.0-or-later
"""Which files have grown past the point of being usable, and which want SPLITTING.

A REPORT, never a gate — it exits 0 whatever it finds.  `M-file-sizes` on the release
checklist reads it at the cycle's halfway point.

Length alone is not a defect.  DOC_QUALITY.md rule 4 judges a comment by content and
says so plainly ("a 70-line module header can be right"), and the same holds for a
file: a long chapter about ONE subject is a long chapter, not a problem.  What makes a
file unusable is holding SEVERAL subjects, because then no reader can hold its shape in
mind and no section can be found without scrolling.

So the number that decides is not the line count but the SPLIT SIGNAL: the share of the
file taken by its largest section.

    largest section is a SMALL share  ->  many comparable subjects  ->  split per subject
    largest section DOMINATES         ->  one subject, merely long  ->  leave it alone

A file is only reported when it is over its kind's bar AND the signal says something,
so the list stays short enough to act on.  Generated files are marked and never
flagged: nobody reads them and splitting them would be undone by the next build.

    scripts/file-sizes.py                # the report
    scripts/file-sizes.py --all          # every file over the bar, not just the top
    scripts/file-sizes.py --doc-bar 600  # move a bar
"""

from __future__ import annotations

import argparse
import os
import re
import subprocess
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

# A file over its kind's bar is a CANDIDATE, nothing more — the split signal decides.
# The bars are set where a file stops fitting in one reading rather than at a round
# number: a doc past ~700 lines no longer renders as one page a reader scrolls, and a
# source file past ~1200 lines stops fitting the "one file, one subject" test the
# module tree is built on.
DOC_BAR = 700
CODE_BAR = 1200

# Below this share, the largest section is not the file's subject — it is one of
# several, which is what "split per subject" means mechanically.
SPLIT_SHARE = 0.25
# Above this share, one section IS the file; length is then a property of the subject.
WHOLE_SHARE = 0.50

SKIP_DIRS = {
    ".git",
    "target",
    "node_modules",
    "doc/pkg",
    "tests/generated",
    ".loft",
    "native-auto",
}

# What starts a new SUBJECT in each kind of file.
DOC_SECTION = re.compile(r"^##\s+\S")
RUST_ITEM = re.compile(
    r"^(?:pub(?:\([^)]*\))?\s+)?(?:default\s+)?(?:const\s+)?(?:async\s+)?"
    r"(?:unsafe\s+)?(?:extern\s+\"[^\"]*\"\s+)?"
    r"(?:fn|struct|enum|trait|impl|mod|union|macro_rules!)\b"
)
PY_ITEM = re.compile(r"^(?:def|class)\s+\S")

GENERATED = re.compile(r"@generated|DO NOT EDIT|Generated by|autogenerated", re.I)


def tracked_files() -> list[str]:
    """Only what git tracks — a build artefact is not a file anyone maintains."""
    out = subprocess.run(
        ["git", "-C", ROOT, "ls-files"], capture_output=True, text=True, check=False
    )
    return [p for p in out.stdout.splitlines() if p]


def kind_of(path: str) -> str | None:
    if any(path == d or path.startswith(d + "/") for d in SKIP_DIRS):
        return None
    if path.endswith(".md"):
        return "doc"
    if path.endswith(".rs"):
        return "code"
    if path.endswith(".py") and path.startswith("scripts/"):
        return "code"
    return None


def sections(lines: list[str], kind: str, path: str) -> list[tuple[str, int]]:
    """(title, length) per top-level section, in file order.

    The anchors are deliberately column-0 only.  A nested `fn` inside an `impl` is part
    of that impl's subject, not a subject of its own, and counting it as one would make
    every Rust file look like dozens of tiny subjects and so always "splittable".

    Known limit: an anchor spelling that appears at column 0 inside a STRING LITERAL is
    counted as a section — the code generator's emission templates do this, which is why
    `src/generation/mod.rs` names `fn loft_ckpt_report() {{` as its biggest.  The report
    is a reading aid, so a handful of misread anchors cost a line of judgement, not a
    wrong answer; parsing Rust properly to fix it would cost far more than it returns.
    """
    if kind == "doc":
        anchor = DOC_SECTION
    elif path.endswith(".py"):
        anchor = PY_ITEM
    else:
        anchor = RUST_ITEM

    marks = [i for i, ln in enumerate(lines) if anchor.match(ln)]
    if not marks:
        return []
    out = []
    for n, start in enumerate(marks):
        end = marks[n + 1] if n + 1 < len(marks) else len(lines)
        out.append((lines[start].strip()[:60], end - start))
    return out


def verdict(total: int, secs: list[tuple[str, int]]) -> tuple[str, str]:
    """The recommendation, and the reason a reader can check.

    The share is measured against the SPANNED body (first anchor to EOF), not against
    the file, because the sections do not cover the preamble above the first one.
    Dividing by the file made a doc with a single late `##` report a 2 % "largest
    section" and so read as several subjects — a denominator that did not match its
    subject.  A file with fewer than two sections cannot be split along anything, and
    is answered as such rather than scored.
    """
    if len(secs) < 2:
        return "KEEP", (
            "no top-level sections — nothing to split along"
            if not secs
            else "one top-level section — nothing to split along"
        )
    spanned = sum(n for _, n in secs) or total
    biggest = max(secs, key=lambda s: s[1])
    share = biggest[1] / spanned
    if share >= WHOLE_SHARE:
        return (
            "KEEP",
            f"one section is {share:.0%} of the file ({biggest[0]}) — "
            f"a single subject that is merely long",
        )
    if share < SPLIT_SHARE:
        return (
            "SPLIT",
            f"{len(secs)} sections, the largest only {share:.0%} "
            f"— comparable subjects sharing a file",
        )
    return (
        "look",
        f"{len(secs)} sections, largest {share:.0%} ({biggest[0]}) "
        f"— a dominant subject with real company",
    )


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--doc-bar", type=int, default=DOC_BAR)
    ap.add_argument("--code-bar", type=int, default=CODE_BAR)
    ap.add_argument("--all", action="store_true", help="every file over the bar")
    ap.add_argument("--top", type=int, default=15)
    args = ap.parse_args()

    rows: dict[str, list] = {"doc": [], "code": []}
    totals: dict[str, list[int]] = {"doc": [], "code": []}

    for rel in tracked_files():
        kind = kind_of(rel)
        if not kind:
            continue
        full = os.path.join(ROOT, rel)
        try:
            with open(full, encoding="utf-8", errors="replace") as f:
                text = f.read()
        except OSError:
            continue
        lines = text.splitlines()
        n = len(lines)
        totals[kind].append(n)
        bar = args.doc_bar if kind == "doc" else args.code_bar
        if n < bar:
            continue
        gen = bool(GENERATED.search(text[:4000]))
        secs = sections(lines, kind, rel)
        what, why = ("generated", "machine-written — not a file anyone reads") if gen else verdict(n, secs)
        rows[kind].append((n, rel, what, why))

    print("file sizes — which files are too long to use, and which want SPLITTING")
    print("(a REPORT, never a gate.  Length is the candidate; the split signal decides.)\n")

    for kind, label, bar in (
        ("doc", "DOCUMENTATION", args.doc_bar),
        ("code", "CODE", args.code_bar),
    ):
        all_n = sorted(totals[kind])
        over = sorted(rows[kind], reverse=True)
        shown = over if args.all else over[: args.top]
        med = all_n[len(all_n) // 2] if all_n else 0
        print(f"== {label}: {len(all_n)} files, median {med} lines, {len(over)} over {bar}")
        if not over:
            print("   nothing over the bar\n")
            continue
        split = [r for r in over if r[2] == "SPLIT"]
        print(f"   {len(split)} of them read as SEVERAL SUBJECTS sharing a file\n")
        for n, rel, what, why in shown:
            print(f"  {n:>6}  {what:<9} {rel}")
            print(f"          {why}")
        if len(over) > len(shown):
            print(f"\n   ... {len(over) - len(shown)} more over the bar (--all)")
        print()

    print("SPLIT = split per subject · KEEP = one long subject, leave it · look = judgement")
    print("Bars are candidates, not verdicts: --doc-bar / --code-bar move them.")
    return 0


if __name__ == "__main__":
    sys.exit(main())
