#!/usr/bin/env python3
# Copyright (c) 2026 Jurjen Stellingwerff
# SPDX-License-Identifier: LGPL-3.0-or-later
"""Which files have grown past the point of being usable, and which want SPLITTING.

A REPORT, never a gate — it exits 0 whatever it finds.  `M-file-sizes` on the release
checklist reads it at the cycle's halfway point.

Length alone is not a defect.  DOC_QUALITY.md rule 4 judges a comment by content and
says so plainly ("a 70-line module header can be right"), and the same holds for a
file: a long chapter about ONE subject is a long chapter, not a problem.  What makes a
file unusable is holding SEVERAL subjects, because then no reader can hold its shape in
mind and no section can be found without scrolling.

So the number that decides is not the line count but the SPLIT SIGNAL: the share of the
file taken by its largest section.

    largest section is a SMALL share  ->  many comparable subjects  ->  split per subject
    largest section DOMINATES         ->  one subject, merely long  ->  leave it alone

A file is only reported when it is over its kind's bar AND the signal says something,
so the list stays short enough to act on.  Generated files are marked and never
flagged: nobody reads them and splitting them would be undone by the next build.

    scripts/file-sizes.py                # the report
    scripts/file-sizes.py --all          # every file over the bar, not just the top
    scripts/file-sizes.py --doc-bar 600  # move a bar
    scripts/file-sizes.py --pick 2       # this release's split picks, with a first seam grouping
"""

from __future__ import annotations

import argparse
import os
import re
import subprocess
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

# A doc over DOC_BAR breaks a rule: 1000 lines is the hard ceiling for a maintainer doc
# (DOC_QUALITY.md § Maintainer docs, rule 2).  A source file over CODE_BAR is a CANDIDATE,
# nothing more — the split signal decides; past ~1200 lines it stops fitting the "one file,
# one subject" test the module tree is built on.
DOC_BAR = 1000
CODE_BAR = 1200

# Below this share, the largest section is not the file's subject — it is one of
# several, which is what "split per subject" means mechanically.
SPLIT_SHARE = 0.25
# Above this share, one section IS the file; length is then a property of the subject.
WHOLE_SHARE = 0.50

SKIP_DIRS = {
    ".git",
    "target",
    "node_modules",
    "doc/pkg",
    "tests/generated",
    ".loft",
    "native-auto",
}

# What starts a new SUBJECT in each kind of file.
DOC_SECTION = re.compile(r"^##\s+\S")
RUST_ITEM = re.compile(
    r"^(?:pub(?:\([^)]*\))?\s+)?(?:default\s+)?(?:const\s+)?(?:async\s+)?"
    r"(?:unsafe\s+)?(?:extern\s+\"[^\"]*\"\s+)?"
    r"(?:fn|struct|enum|trait|impl|mod|union|macro_rules!)\b"
)
# A block whose ITEMS are the subjects, not the block itself.
TRANSPARENT = re.compile(r"^(?:pub(?:\([^)]*\))?\s+)?(?:unsafe\s+)?(?:impl\b|mod\s)")
PY_ITEM = re.compile(r"^(?:def|class)\s+\S")

GENERATED = re.compile(r"@generated|DO NOT EDIT|Generated by|autogenerated", re.I)


def tracked_files() -> list[str]:
    """Only what git tracks — a build artefact is not a file anyone maintains."""
    out = subprocess.run(
        ["git", "-C", ROOT, "ls-files"], capture_output=True, text=True, check=False
    )
    return [p for p in out.stdout.splitlines() if p]


def kind_of(path: str) -> str | None:
    if any(path == d or path.startswith(d + "/") for d in SKIP_DIRS):
        return None
    if path.endswith(".md"):
        return "doc"
    if path.endswith(".rs"):
        return "code"
    if path.endswith(".py") and path.startswith("scripts/"):
        return "code"
    return None


def sections(lines: list[str], kind: str, path: str) -> list[tuple[str, int]]:
    """(title, length) per section, in file order.

    Docs and Python section on their column-0 anchors.  Rust sections on ITEMS, and an
    `impl` or inline `mod` block is TRANSPARENT: its items are the sections, one level in.
    In Rust an `impl` block is a container, not a subject — one `impl Parser` may be spread
    over any number of files — so counting it as one section made a 20 000-line file of
    small methods read as "one subject, merely long".  A `#[cfg(test)]` module stays one
    section: its tests move as a whole.  Items nested deeper (a `fn` inside a `fn`) belong
    to their enclosing item.

    Known limit: an anchor spelling that appears at an item's indent inside a STRING
    LITERAL is counted as a section — the code generator's emission templates do this,
    which is why `src/generation/mod.rs` names `fn loft_ckpt_report() {{` as its biggest.
    The report is a reading aid, so a handful of misread anchors cost a line of judgement,
    not a wrong answer; parsing Rust properly to fix it would cost far more than it returns.
    """
    if kind == "doc" or path.endswith(".py"):
        anchor = DOC_SECTION if kind == "doc" else PY_ITEM
        marks = [i for i, ln in enumerate(lines) if anchor.match(ln)]
        ends = marks[1:] + [len(lines)]
        return [(lines[a].strip()[:60], b - a) for a, b in zip(marks, ends)]
    return [(lines[a].strip()[:60], b - a) for a, b in rust_items(lines, 0, len(lines), "")]


def rust_items(lines: list[str], lo: int, hi: int, indent: str) -> list[tuple[int, int]]:
    """(start, end) of each section among lines[lo:hi] whose items sit at `indent`.

    A section runs from its item line to the next item at the same indent (so the doc
    comments and attributes of the NEXT item count with the previous one — a constant
    offset per item that does not move a share).  A transparent block is replaced by its
    own items; its closing brace, the first line after it that is `indent + "}"`, ends it.
    """
    marks = [i for i in range(lo, hi) if lines[i].startswith(indent) and RUST_ITEM.match(lines[i][len(indent):])]
    out: list[tuple[int, int]] = []
    for n, start in enumerate(marks):
        end = marks[n + 1] if n + 1 < len(marks) else hi
        head = lines[start][len(indent):]
        if TRANSPARENT.match(head) and head.rstrip().endswith("{") and not is_test_mod(lines, start):
            close = next((i for i in range(start + 1, end) if lines[i] == indent + "}"), None)
            if close is not None:
                inner = rust_items(lines, start + 1, close, indent + "    ")
                if inner:
                    out.extend(inner)
                    continue
        out.append((start, end))
    return out


def is_test_mod(lines: list[str], at: int) -> bool:
    """Whether the item at `at` is a module under `#[cfg(test)]`."""
    if not re.match(r"\s*(?:pub(?:\([^)]*\))?\s+)?mod\b", lines[at]):
        return False
    i = at - 1
    while i >= 0 and lines[i].strip().startswith(("#[", "//")):
        if lines[i].strip().startswith("#[cfg(test)]"):
            return True
        i -= 1
    return False


def verdict(total: int, secs: list[tuple[str, int]]) -> tuple[str, str]:
    """The recommendation, and the reason a reader can check.

    The share is measured against the SPANNED body (first anchor to EOF), not against
    the file, because the sections do not cover the preamble above the first one.
    Dividing by the file made a doc with a single late `##` report a 2 % "largest
    section" and so read as several subjects — a denominator that did not match its
    subject.  A file with fewer than two sections cannot be split along anything, and
    is answered as such rather than scored.
    """
    if len(secs) < 2:
        return "KEEP", (
            "no top-level sections — nothing to split along"
            if not secs
            else "one top-level section — nothing to split along"
        )
    spanned = sum(n for _, n in secs) or total
    biggest = max(secs, key=lambda s: s[1])
    share = biggest[1] / spanned
    if share >= WHOLE_SHARE:
        return (
            "KEEP",
            f"one section is {share:.0%} of the file ({biggest[0]}) — "
            f"a single subject that is merely long",
        )
    if share < SPLIT_SHARE:
        return (
            "SPLIT",
            f"{len(secs)} sections, the largest only {share:.0%} "
            f"— comparable subjects sharing a file",
        )
    return (
        "look",
        f"{len(secs)} sections, largest {share:.0%} ({biggest[0]}) "
        f"— a dominant subject with real company",
    )


def split_value(secs: list[tuple[str, int]]) -> int:
    """Lines a split can move: the spanned body minus its largest section.

    This ranks the pick.  A file of many comparable items scores close to its length; a
    file that is one long item scores close to zero, however long it is — splitting it
    moves nothing, and the length is that item's own `too_many_lines` question.
    """
    if len(secs) < 2:
        return 0
    return sum(n for _, n in secs) - max(n for _, n in secs)


FN_NAME = re.compile(r"\bfn\s+([A-Za-z_][A-Za-z0-9_]*)")
CALL = re.compile(r"\b([A-Za-z_][A-Za-z0-9_]*)\s*\(")


def seams(lines: list[str], limit: int = 8) -> list[str]:
    """A FIRST grouping of a Rust file's items, for the split-file skill to refine.

    Items are grouped by name stem (the first word of a snake_case fn name, or its first
    two when one stem holds over a third of the file), types and constants apart.  Each
    group is printed with its size and the group it calls most outside itself, which is
    where a seam between two groups would cut the most calls.  Names are a proxy for
    subject, never a rule: the skill reads the code before choosing a seam.
    """
    items = rust_items(lines, 0, len(lines), "")
    fns: dict[str, tuple[int, int]] = {}
    other = 0
    for a, b in items:
        m = FN_NAME.search(lines[a])
        if m and not lines[a].lstrip().startswith(("mod ", "pub mod ", "struct", "pub struct", "enum", "pub enum")):
            fns[m.group(1)] = (a, b)
        else:
            other += b - a
    total = sum(b - a for a, b in fns.values()) + other or 1

    def stem(name: str, depth: int) -> str:
        parts = [p for p in name.split("_") if p]
        return "_".join(parts[:depth]) or name

    group = {n: stem(n, 1) for n in fns}
    sizes: dict[str, int] = {}
    for n, g in group.items():
        sizes[g] = sizes.get(g, 0) + fns[n][1] - fns[n][0]
    for g, size in list(sizes.items()):
        if size * 3 > total:
            for n in [n for n, h in group.items() if h == g]:
                group[n] = stem(n, 2)
    sizes, counts, calls = {}, {}, {}
    for n, (a, b) in fns.items():
        g = group[n]
        sizes[g] = sizes.get(g, 0) + b - a
        counts[g] = counts.get(g, 0) + 1
        out = calls.setdefault(g, {})
        for c in CALL.findall("\n".join(lines[a + 1 : b])):
            h = group.get(c)
            if h and h != g:
                out[h] = out.get(h, 0) + 1
    rows = []
    if other:
        rows.append(f"{other:>6}  types, consts, modules")
    for g in sorted(sizes, key=lambda g: -sizes[g])[:limit]:
        near = max(calls[g].items(), key=lambda kv: kv[1], default=None)
        tail = f" — calls {near[0]}_* most ({near[1]})" if near else " — calls no other group"
        rows.append(f"{sizes[g]:>6}  {g}_* ({counts[g]} fns){tail}")
    if len(sizes) > limit:
        rows.append(f"        ... {len(sizes) - limit} smaller groups")
    return rows


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--doc-bar", type=int, default=DOC_BAR)
    ap.add_argument("--code-bar", type=int, default=CODE_BAR)
    ap.add_argument("--all", action="store_true", help="every file over the bar")
    ap.add_argument("--top", type=int, default=15)
    ap.add_argument(
        "--pick",
        type=int,
        metavar="N",
        help="the N code files this release splits, by split value, with a first seam grouping",
    )
    args = ap.parse_args()

    rows: dict[str, list] = {"doc": [], "code": []}
    totals: dict[str, list[int]] = {"doc": [], "code": []}

    for rel in tracked_files():
        kind = kind_of(rel)
        if not kind:
            continue
        full = os.path.join(ROOT, rel)
        try:
            with open(full, encoding="utf-8", errors="replace") as f:
                text = f.read()
        except OSError:
            continue
        lines = text.splitlines()
        n = len(lines)
        totals[kind].append(n)
        bar = args.doc_bar if kind == "doc" else args.code_bar
        if n < bar:
            continue
        gen = bool(GENERATED.search(text[:4000]))
        secs = sections(lines, kind, rel)
        what, why = ("generated", "machine-written — not a file anyone reads") if gen else verdict(n, secs)
        rows[kind].append((n, rel, what, why, split_value(secs) if not gen else 0, lines))

    if args.pick:
        return pick(rows["code"], args.pick)

    print("file sizes — which files are too long to use, and which want SPLITTING")
    print("(a REPORT, never a gate.  Length is the candidate; the split signal decides.)\n")

    for kind, label, bar in (
        ("doc", "DOCUMENTATION", args.doc_bar),
        ("code", "CODE", args.code_bar),
    ):
        all_n = sorted(totals[kind])
        over = sorted(rows[kind], key=lambda r: (-r[0], r[1]))
        shown = over if args.all else over[: args.top]
        med = all_n[len(all_n) // 2] if all_n else 0
        print(f"== {label}: {len(all_n)} files, median {med} lines, {len(over)} over {bar}")
        if not over:
            print("   nothing over the bar\n")
            continue
        split = [r for r in over if r[2] == "SPLIT"]
        print(f"   {len(split)} of them read as SEVERAL SUBJECTS sharing a file\n")
        for n, rel, what, why, _, _ in shown:
            print(f"  {n:>6}  {what:<9} {rel}")
            print(f"          {why}")
        if len(over) > len(shown):
            print(f"\n   ... {len(over) - len(shown)} more over the bar (--all)")
        print()

    print("SPLIT = split per subject · KEEP = one long subject, leave it · look = judgement")
    print("Bars are candidates, not verdicts: --doc-bar / --code-bar move them.")
    return 0


def pick(code: list, n: int) -> int:
    """`M-file-split`'s input: the files this release splits, most movable lines first.

    Only SPLIT and `look` files are candidates — a KEEP file is one long subject, and a
    generated one is rewritten by its generator.  Writes nothing; the checklist tick
    records the pick's commit.
    """
    cands = sorted(
        (r for r in code if r[2] in ("SPLIT", "look")), key=lambda r: (-r[4], r[1])
    )
    print(f"the split pick — {min(n, len(cands))} of {len(cands)} candidate files, by split value")
    print("(split value = lines a split can move: the file minus its largest item)\n")
    for total, rel, what, why, value, lines in cands[:n]:
        print(f"  {rel}  {total} lines, split value {value}  [{what}]")
        print(f"          {why}")
        if rel.endswith(".rs"):
            print("        first grouping (by name stem — refine it, do not follow it):")
            for row in seams(lines):
                print(f"        {row}")
        print()
    print("Split the first with the split-file skill; one file per PR, moves only.")
    return 0


if __name__ == "__main__":
    sys.exit(main())
