#!/usr/bin/env bash
# Detect UNMERGED branches across the loft-libs-* repos — squash-merge safe.
#
# Why not `git merge-base --is-ancestor` / `ahead_by`?  Squash-merge rewrites a
# branch's commits into ONE new commit on the default branch, so the branch's
# originals are never ancestors — every merged branch then looks "unmerged" by
# commit graph.  Instead we compare CONTENT: for the files a branch changed since
# it forked, is the branch's version already identical to the default branch?  If
# yes (squash-merged, or merged any way), it is merged regardless of SHAs.
#
# Usage:
#   lib-branch-audit.sh                 # the full table (every non-default branch) — default
#   lib-branch-audit.sh --markdown [f]  # a committed-doc view of ONLY the unmerged branches
#                                       # (idempotent: no timestamp in the body), to stdout or f
set -uo pipefail

MODE=table
OUT=
while [ $# -gt 0 ]; do
  case "$1" in
    --markdown) MODE=markdown; shift; if [ $# -gt 0 ] && [ "${1#-}" = "$1" ]; then OUT="$1"; shift; fi ;;
    -h|--help) sed -n '11,15p' "$0"; exit 0 ;;
    *) echo "usage: lib-branch-audit.sh [--markdown [outfile]]" >&2; exit 2 ;;
  esac
done

REPOS=(assets core docs game graphics net world)
WORK=$(mktemp -d); trap 'rm -rf "$WORK"' EXIT

rows=()   # one "repo|branch|pr|status" per non-default branch, in repo order
for repo in "${REPOS[@]}"; do
  R="loft-lang/loft-libs-$repo"
  def=$(gh repo view "$R" --json defaultBranchRef --jq '.defaultBranchRef.name' 2>/dev/null) || continue
  git clone --quiet --filter=blob:none "https://github.com/$R.git" "$WORK/$repo" 2>/dev/null || continue
  G=(git -C "$WORK/$repo")
  "${G[@]}" fetch --quiet origin '+refs/heads/*:refs/remotes/origin/*' 2>/dev/null
  for b in $("${G[@]}" for-each-ref --format='%(refname:short)' refs/remotes/origin \
              | sed 's|^origin/||' | grep -vxE "$def|HEAD|origin"); do
    # Files the branch changed since it forked (three-dot: excludes default-ahead-only files).
    mapfile -t files < <("${G[@]}" diff --name-only "origin/$def...origin/$b" 2>/dev/null)
    if [ "${#files[@]}" -eq 0 ] || "${G[@]}" diff --quiet "origin/$def" "origin/$b" -- "${files[@]}" 2>/dev/null; then
      status="merged (content on $def — safe to delete)"
    else
      last=$("${G[@]}" log -1 --format='%s' "origin/$b" 2>/dev/null | cut -c1-46)
      status="UNMERGED (${#files[@]} files) — $last"
    fi
    pr=$(gh pr list --repo "$R" --head "$b" --state all --json number,state,isDraft \
          --jq 'if length==0 then "no-PR" else (.[0] | "#\(.number) \(.state|ascii_downcase)\(if .isDraft then "/draft" else "" end)") end' 2>/dev/null)
    rows+=("$repo|$b|$pr|$status")
  done
done

if [ "$MODE" = table ]; then
  printf "%-9s %-40s %-16s %s\n" REPO BRANCH PR STATUS
  printf '%.0s-' {1..100}; echo
  for r in "${rows[@]}"; do
    IFS='|' read -r repo b pr status <<<"$r"
    printf "%-9s %-40s %-16s %s\n" "$repo" "$b" "$pr" "$status"
  done
  exit 0
fi

# --- markdown mode: a committed doc of ONLY the unmerged branches -----------------------
emit() { if [ -n "$OUT" ]; then printf '%s\n' "$1" >>"$OUT"; else printf '%s\n' "$1"; fi; }
[ -n "$OUT" ] && : >"$OUT"

# Count unmerged + orphans (UNMERGED with no OPEN pr — the actionable, stranded ones).
unmerged=0 orphans=0 repos_seen=""
for r in "${rows[@]}"; do
  IFS='|' read -r repo b pr status <<<"$r"
  case "$status" in UNMERGED*) : ;; *) continue ;; esac
  unmerged=$((unmerged + 1))
  case " $repos_seen " in *" $repo "*) : ;; *) repos_seen="$repos_seen $repo" ;; esac
  case "$pr" in *" open"*) : ;; *) orphans=$((orphans + 1)) ;; esac
done
nrepos=$(printf '%s' "$repos_seen" | wc -w | tr -d ' ')

emit "<!-- generated by scripts/lib-branch-audit.sh --markdown — do not hand-edit; refreshed by the nightly lib-branch-report workflow -->"
emit ""
emit "# In-flight library branches (unmerged)"
emit ""
emit "Unmerged branches across the \`loft-lang/loft-libs-*\` repos — in-flight or stranded library"
emit "work not yet on each repo's default branch. Squash-merge safe (compared by CONTENT, not"
emit "ancestry). The current installable/origin-main API is \`doc/claude/LIBRARIES.md\`, a local build (\`make libcatalogue\`, not committed); this is"
emit "the branch-level view of what is still IN FLIGHT. A branch with an **open PR** is active; one"
emit "that is **unmerged with no open PR** is an *orphan* — stranded work to land or delete."
emit "Source: \`scripts/lib-branch-audit.sh\` (@PLN112 / @PLN20 lib-health)."
emit ""
if [ "$unmerged" -eq 0 ]; then
  emit "**All loft-libs-* repos are clean — no unmerged branches.**"
else
  emit "**${unmerged} unmerged branch(es) across ${nrepos} repo(s); ${orphans} orphan(s) (unmerged, no open PR).**"
  last_repo=
  for r in "${rows[@]}"; do
    IFS='|' read -r repo b pr status <<<"$r"
    case "$status" in UNMERGED*) : ;; *) continue ;; esac
    if [ "$repo" != "$last_repo" ]; then emit ""; emit "## loft-libs-$repo"; emit ""; last_repo="$repo"; fi
    detail="${status#UNMERGED }"                       # "(N files) — <subject>"
    orphan=""; case "$pr" in *" open"*) : ;; *) orphan="  ⚠ orphan" ;; esac
    emit "- \`$b\` — PR $pr · $detail$orphan"
  done
fi
