#!/usr/bin/env bash
# Copyright (c) 2026 Jurjen Stellingwerff
# SPDX-License-Identifier: LGPL-3.0-or-later
#
# @PLN159 phase D — print the nextest flag that runs the diff's own subjects FIRST, or
# print nothing.
#
# `make ci` is fail-fast, so the order decides when a red gate says so: the binaries a
# diff touches going first turns "whenever the pool reaches it" into the first minute.
# Coverage is untouched — this is an ORDER, expressed as a nextest `priority` override
# in a tool config file, which layers UNDER .config/nextest.toml: the repo config keeps
# its groups and timeouts, and only `priority`, which it never sets, comes from here.
#
# Prints nothing (so the gate runs in its default order) when the diff maps to no
# subject, or touches something every binary depends on — `changed_filter` in
# test_subjects.sh decides that, and says why on stderr.
#
#   cargo nextest run --profile ci $(scripts/nextest_priority.sh [ref])
set -euo pipefail
ROOT=$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)
# shellcheck source=scripts/test_subjects.sh
source "$ROOT/scripts/test_subjects.sh"
f=$(cd "$ROOT" && changed_filter "${1:-HEAD}") || exit 0
[[ -n "$f" ]] || exit 0
out="$ROOT/target/nextest-changed-first.toml"
mkdir -p "$ROOT/target"
printf '# generated by scripts/nextest_priority.sh — the diff'"'"'s subjects run first\n[[profile.ci.overrides]]\nfilter = %s\npriority = 100\n' "'$f'" > "$out"
echo "--tool-config-file loft-changed-first:$out"
