#!/usr/bin/env python3
# Copyright (c) 2026 Jurjen Stellingwerff
# SPDX-License-Identifier: LGPL-3.0-or-later
"""@PLN160 — do `τ` and `τ?` reach the store machinery by the same road?

@PLN153 asked *"does this rule have one home?"* and gave the null rules one each; its phase-6
re-measure said the class did not fall.  Reading the residual named a mechanism that plan never
touched: **the nullable spelling takes a different LOWERING from its dense twin, so every
ownership decision downstream is posed a second time and answered once.**

`@FR-N-Shape` already settled the TYPE-side half — a shape question answers alike for `τ` and
`τ?`.  This is the LOWERING-side half, and it has no rule yet.  So the plan opens on a
measurement rather than a design: **enumerate where the two lowerings diverge**, then ask of
each whether C90 REQUIRES it (the `?` is a compile-time marker, so most cannot) or whether it is
an accident of the site that introduced it.

The instrument is `introspect_diff.sh`'s idea pointed at one compiler and two PROGRAMS: emit the
dense spelling and its nullable twin, normalise away the `?` itself, and diff what is left.  A
difference that survives is a road one spelling takes and the other does not.

## The corpus is PAIRS, written by hand

`doc/claude/plans/160-nullable-road/pairs/<name>.dense.loft` and `<name>.opt.loft`.  Hand-written
rather than generated by inserting a `?`, because what counts as "the twin" is a judgement per
shape — a nullable RETURN, a nullable LOCAL and a nullable ELEMENT are three different edits —
and a generator would silently produce a pair that is not a pair.  Each file says in a comment
which issue's shape it is.

## What the normalisation removes, and what it must not

Removed: the `?` marker on a type, the absolute source path, and the `loft:…:<line>` position
comments — all three differ between two files by construction and say nothing about the road.

**Kept: everything else, including variable NUMBERING and temp COUNTS.**  An extra `__retbuf`,
an extra work-ref, a materialisation on one side only — those ARE the finding, so normalising
them away would be normalising away the answer.

Usage:
    scripts/nullable_road.py                 # every pair, one verdict each
    scripts/nullable_road.py --diff <name>   # the surviving diff for one pair
    scripts/nullable_road.py --control       # the instrument's own positive control
"""
import argparse
import difflib
import os
import re
import subprocess
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
PAIRS = os.path.join(ROOT, "doc", "claude", "plans", "160-nullable-road", "pairs")

# The `?` marker itself, wherever a type carries it.  `S?`, `ref(S)["p"]?`, `vector<S>?`.
OPT_MARK = re.compile(r"(?<=[\w\)\]>])\?")
# Absolute paths and position comments: both differ between two files by construction.
PATHS = re.compile(r"/\S*?\.loft")
POSLINE = re.compile(r"^\s*// loft:.*$", re.M)
# The generated Rust carries the pair's own file name in live-dispatch ids and span comments.
NOISE = re.compile(r"^\s*(?://.*)?$")
# ⚠ Three kinds of noise the first version reported as findings, each caught by reading a
# divergence instead of believing it.  `keyed-view-write` came back +4/-4 and every one of the
# four lines was an artefact of this script:
#
#   * SOURCE LINE NUMBERS — `[4]` statement markers and `cr_call_push(…, 4)` — which differ
#     whenever the two halves have a different number of header comment lines, i.e. always;
#   * COLUMN PADDING — stripping the `?` out of `hash(731)?` shortens the token and shifts the
#     aligned column after it, so a dump table row differs by whitespace alone;
#   * and the position comments already handled above.
#
# A measurement whose smallest result is entirely its own noise has not measured anything.
STMT_POS = re.compile(r"^(\s*)\[\d+\]")
CALL_PUSH = re.compile(r'(cr_call_push\([^,]*,\s*"[^"]*",\s*)\d+')
# A bytecode line is `<pc>[<stack depth>]: [<source line>] <op> … var=x[<offset>]`.  ONLY the
# third bracket is a source line; the depth and every `var=…[offset]` are real information and
# erasing them would hide the very divergence this looks for — an extra temp shifts offsets.
# The first attempt matched `\[\d+\](?=:)` and normalised `x[72]:` into `x[<line>]:`, which is a
# variable's slot.  Anchored on the `pc[depth]: ` prefix now.
BYTECODE_POS = re.compile(r"^(\s*\d+\[\d+\]:\s*)\[\d+\]")
WS = re.compile(r"[ \t]+")


def loft_bin():
    for p in ("target/debug/loft", "target/release/loft"):
        if os.path.exists(os.path.join(ROOT, p)):
            return os.path.join(ROOT, p)
    sys.exit("no loft binary — `cargo build --bin loft` first")


def introspect(path):
    out = subprocess.run(
        [loft_bin(), "--path", ROOT, "introspect", path],
        capture_output=True, text=True, cwd=ROOT, timeout=180,
    )
    return out.stdout + out.stderr


def normalise(text, stem):
    """Strip the `?` marker, the paths and the position comments — and nothing else."""
    text = POSLINE.sub("", text)
    text = PATHS.sub("<file>", text)
    text = text.replace(stem, "<stem>")
    text = OPT_MARK.sub("", text)
    text = CALL_PUSH.sub(r"\g<1><line>", text)
    out = []
    for l in text.split("\n"):
        if NOISE.match(l):
            continue
        l = STMT_POS.sub(r"\1[<line>]", l)
        l = BYTECODE_POS.sub(r"\1[<line>]", l)
        # Collapse runs of whitespace LAST: the `?` strip above shortens tokens and shifts every
        # aligned column after them, which is a difference in this script and not in the tree.
        out.append(WS.sub(" ", l).rstrip())
    return out


def pair_names():
    if not os.path.isdir(PAIRS):
        return []
    return sorted(
        f[: -len(".dense.loft")]
        for f in os.listdir(PAIRS)
        if f.endswith(".dense.loft")
        and os.path.exists(os.path.join(PAIRS, f[: -len(".dense.loft")] + ".opt.loft"))
    )


def diff_of(name):
    d = normalise(introspect(os.path.join(PAIRS, f"{name}.dense.loft")), name)
    o = normalise(introspect(os.path.join(PAIRS, f"{name}.opt.loft")), name)
    return list(difflib.unified_diff(d, o, "dense", "nullable", n=1, lineterm=""))


# The MACHINERY channels a divergence can be made of.  A whole-diff verdict is too coarse to
# classify with — measured: `ret-view-of-param-vector` diverges by 188 lines while its return
# BUFFER is perfectly symmetric, so "diverges" said nothing about the question being asked.
# Counting per channel separates the road from the noise: a `__ncc_` asymmetry is the `??`
# operator a nullable twin cannot avoid writing, and a `__retbuf` asymmetry is a delivery one
# spelling gets and the other does not.
CHANNELS = {
    "retbuf": r"__retbuf",
    "ncc(??)": r"__ncc_",
    "materialise": r"materiali[sz]",
    "copy-record": r"OpCopyRecord",
    "free-ref": r"OpFreeRef",
    "mint": r"OpDatabase",
    "work-ref": r"__ref_",
}


def channels(name):
    """Per-channel counts in each half, and the ones that DIFFER."""
    out = {}
    for half in ("dense", "opt"):
        text = introspect(os.path.join(PAIRS, f"{name}.{half}.loft"))
        out[half] = {k: len(re.findall(v, text)) for k, v in CHANNELS.items()}
    return {k: (out["dense"][k], out["opt"][k])
            for k in CHANNELS if out["dense"][k] != out["opt"][k]}


def headline(name):
    """The first line of the pair's own `//` header — what shape it is."""
    p = os.path.join(PAIRS, f"{name}.dense.loft")
    for line in open(p, encoding="utf-8"):
        m = re.match(r"//\s*(\S.*)$", line)
        if m and not m.group(1).startswith(("Copyright", "SPDX")):
            return m.group(1)
    return ""


def run_pair_half(path, native):
    """Run one half, returning (value, leak_note).  BOTH backends reachable.

    The leak channel needs TWO greps, not one.  `LOFT_STRICT_STORES=1` implies
    `LOFT_NO_SLOT_REUSE` (`keys.rs`), so a leak-FREE program that churns more than 65535
    stores ABORTS with *"store table exhausted"* rather than finishing — and a sweep that
    greps only for `strict-store`, the obvious thing to grep, sees no such line and scores
    that file CLEAN.  Measured on a 45-file sweep where 1 file did exactly that.
    """
    cmd = [loft_bin(), "--path", ROOT]
    if not native:
        cmd.append("--interpret")
    cmd.append(path)
    env = dict(os.environ, LOFT_STRICT_STORES="1", LOFT_TIMEOUT="90")
    try:
        out = subprocess.run(cmd, capture_output=True, text=True, cwd=ROOT,
                             timeout=240, env=env)
    except subprocess.TimeoutExpired:
        return ("<timeout>", "timeout")
    text = out.stdout + out.stderr
    if "store table exhausted" in text:
        return ("<exhausted>", "EXHAUSTED — re-read under LOFT_STORES=timeline")
    if "strict-store" in text:
        return (text.strip().split("\n")[-1], "LEAK")
    body = [l for l in out.stdout.strip().split("\n") if l.strip()]
    return (body[-1] if body else "", "")


def verify():
    """@PLN160's stated VERIFY: every pair, both halves, BOTH backends, under
    `LOFT_STRICT_STORES=1`.

    The issue asks for exactly this and the channel was being run by hand, which is not a
    measurement the next reader can repeat.  Two things it checks that the IR diff cannot:
    the two halves AGREE IN VALUE (so a surviving diff is a lowering difference and not a
    semantic one — the claim the whole report rests on), and neither half leaks.
    """
    names = pair_names()
    print("\n== @PLN160 verify — both halves, both backends, LOFT_STRICT_STORES=1 ==\n")
    bad = 0
    for n in names:
        cells = {}
        for half in ("dense", "opt"):
            for native in (False, True):
                cells[(half, native)] = run_pair_half(
                    os.path.join(PAIRS, f"{n}.{half}.loft"), native)
        vals = {k: v[0] for k, v in cells.items()}
        notes = [f"{h}/{'native' if nat else 'interp'} {msg}"
                 for (h, nat), (_, msg) in cells.items() if msg]
        agree = len(set(vals.values())) == 1
        ok = agree and not notes
        bad += 0 if ok else 1
        mark = "ok  " if ok else "FAIL"
        print(f"  {mark}  {n:<32} value={next(iter(vals.values()))!r}")
        if not agree:
            print("        halves DISAGREE — a surviving diff would not be a pure lowering "
                  "difference:")
            for k, v in vals.items():
                print(f"          {k[0]}/{'native' if k[1] else 'interp'}: {v!r}")
        for note in notes:
            print(f"        {note}")
    print(f"\n  {len(names) - bad} of {len(names)} pairs verify.\n")
    return 1 if bad else 0


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--diff", metavar="NAME", help="print the surviving diff for one pair")
    ap.add_argument("--control", action="store_true",
                    help="the instrument's own control: a pair that is its own twin")
    ap.add_argument("--verify", action="store_true",
                    help="@PLN160's stated verify: both halves, BOTH backends, "
                         "under LOFT_STRICT_STORES=1")
    a = ap.parse_args()

    names = pair_names()
    if not names:
        sys.exit(f"no pairs under {os.path.relpath(PAIRS, ROOT)}")

    if a.verify:
        return verify()

    if a.control:
        # A file against ITSELF must normalise to nothing.  Without this the whole report is
        # unfalsifiable: a normaliser that flattened everything would call every pair identical
        # and read as "the two spellings agree everywhere".
        name = names[0]
        d = normalise(introspect(os.path.join(PAIRS, f"{name}.dense.loft")), name)
        same = list(difflib.unified_diff(d, d, lineterm=""))
        print(f"CONTROL — {name}.dense against itself: "
              + ("PASS (empty)" if not same else f"FAIL ({len(same)} lines)"))
        # And the other direction: the normaliser must NOT erase a real difference.
        rough = diff_of(name)
        print(f"CONTROL — the same pair's real diff survives normalisation: "
              + ("PASS" if rough else "FAIL — normalisation ate the difference"))
        # ⚠ The control the first version lacked, and the one that matters most: a file against
        # a COSMETICALLY different copy of itself — one extra comment line, so every source
        # line number moves — must normalise to EMPTY.  Without it the report calls its own
        # line-number noise a divergence, which is exactly what it did.
        import tempfile
        src = open(os.path.join(PAIRS, f"{name}.dense.loft"), encoding="utf-8").read()
        with tempfile.TemporaryDirectory() as td:
            shifted = os.path.join(td, f"{name}.dense.loft")
            open(shifted, "w", encoding="utf-8").write("// an extra header line\n" + src)
            a2 = normalise(introspect(shifted), name)
        noise = list(difflib.unified_diff(d, a2, lineterm=""))
        print(f"CONTROL — a cosmetically shifted copy normalises to nothing: "
              + ("PASS" if not noise else f"FAIL ({len(noise)} lines of self-noise)"))
        for l in noise[:8]:
            print(f"    {l}")
        return 0 if not same and rough and not noise else 1

    if a.diff:
        for line in diff_of(a.diff):
            print(line)
        return 0

    print("\n== @PLN160 — where the nullable spelling's lowering leaves its dense twin's ==\n")
    print(f"  {len(names)} pair(s); a SURVIVING diff is a road one spelling takes and the "
          "other does not\n")
    diverge = 0
    for n in names:
        d = diff_of(n)
        ch = channels(n)
        # `??` is the confound: a nullable twin MUST handle absence somewhere, so an `ncc`
        # asymmetry is the operator's own lowering and not the nullable type's road.
        road = {k: v for k, v in ch.items() if k != "ncc(??)"}
        if d:
            diverge += 1
            adds = sum(1 for l in d if l.startswith("+") and not l.startswith("+++"))
            dels = sum(1 for l in d if l.startswith("-") and not l.startswith("---"))
            mark = "DIVERGES" if road else "  ??-only"
            print(f"  {mark}  {n:<32} +{adds} -{dels}")
            for k, (a, b) in sorted(road.items()):
                print(f"      {k:<14} dense {a:4d}   nullable {b:4d}   ({b - a:+d})")
            if not road:
                print("      every asymmetric channel is `??`'s own lowering — no road differs")
        else:
            print(f"  same      {n:<32}")
        print(f"      {headline(n)}")
    print(f"\n  {diverge} of {len(names)} pairs diverge after the `?` itself is normalised away.")
    print("  `--diff <name>` for one.  Each divergence is a question: does C90 REQUIRE it —")
    print("  the `?` is a compile-time marker, so most cannot — or is it an accident of the")
    print("  site that introduced it?  The second kind is the queue.\n")
    return 0


if __name__ == "__main__":
    sys.exit(main())
