#!/usr/bin/env bash
# @PLN179 — the reasons register, read off the tracker: every finding a port met is an
# ISSUE carrying an `axis:` label, and this renders them as REASONS.md.
#
#   scripts/script_reasons.sh            # the markdown register on stdout
#   scripts/script_reasons.sh --count    # the headline number: open axis:* issues
#
# A finding is registered the moment a port meets it, as a bug_report (an answer that is
# wrong or a crash) or a feature_request (a capability loft lacks), with `hit-by:loft`,
# the axis of the bar it failed — axis:behaviour · axis:performance · axis:clarity ·
# axis:environment — and `Found-via: @PLN179 <script>` in the body.  Nothing else is new:
# assessing it is the owner's ordinary triage (sev: / area: / wa:, or closed as not
# planned), tracking it is the existing `Fixes #N` → fixed-pending-merge → closed-on-merge
# automation, and this file is a VIEW that cannot drift from the tracker.  Rows group by
# state, so "what is left to assess" and "what is left to fix" are the first two tables.
# Bash and `gh` today (strand 4's `run` ports it); a box without `gh` reads the committed
# copy and regenerates it elsewhere.
set -uo pipefail
count_only=0; repo="loft-lang/loft"
while [ $# -gt 0 ]; do
  case "$1" in
    --count) count_only=1 ;;
    --repo) shift; repo="$1" ;;
    -h|--help) sed -n '2,19p' "$0" | sed 's/^# \?//'; exit 0 ;;
    *) echo "script_reasons: unknown argument $1" >&2; exit 2 ;;
  esac
  shift
done
command -v gh > /dev/null || { echo "script_reasons: gh is not on this box — read the committed REASONS.md" >&2; exit 2; }
jq_row='.[] | "| \(.number) | \(.title | gsub("\\|"; "\\\\|")) | \(.labels | map(.name) | map(select(startswith("axis:"))) | map(sub("axis:"; "")) | join(" ")) | \(.labels | map(.name) | map(select(startswith("sev:") or startswith("area:") or startswith("wa:") or . == "fixed-pending-merge")) | join(" ")) | \(.state) |"'
fetch() { gh issue list --repo "$repo" --state "$1" --label "$2" --limit 200 --json number,title,labels,state --jq "$jq_row" 2>&1; }
open_rows=""
for ax in behaviour performance clarity environment; do
  r=$(fetch open "axis:$ax") || { echo "script_reasons: cannot ask the tracker — $r" >&2; exit 2; }
  open_rows+="$r"$'\n'
done
open_rows=$(printf '%s' "$open_rows" | grep -c '^|' || true)
if [ "$count_only" = 1 ]; then echo "$open_rows"; exit 0; fi
echo "<!-- Generated by scripts/script_reasons.sh — regenerate with \`make script-reasons\`; never edit by hand. -->"
echo "# @PLN179 — reasons to reach for another tool (driven to zero)"
echo
echo "Every row is an issue with an \`axis:\` label (LABELS.md § axis). **OPEN: $open_rows**"
echo
for section in "To assess — open, not yet triaged|open|untriaged" "Accepted — open, triaged|open|triaged" "Fix landed, awaiting merge|open|pending" "Closed|closed|all"; do
  IFS='|' read -r title state kind <<< "$section"
  echo "## $title"; echo; echo "| # | finding | axis | triage | state |"; echo "|---|---|---|---|---|"
  for ax in behaviour performance clarity environment; do
    fetch "$state" "axis:$ax" | while IFS= read -r line; do
      [ -n "$line" ] || continue
      case "$kind" in
        untriaged) printf '%s\n' "$line" | grep -qE 'sev:|area:|fixed-pending-merge' && continue ;;
        triaged)   printf '%s\n' "$line" | grep -qE 'sev:|area:' || continue; printf '%s\n' "$line" | grep -q fixed-pending-merge && continue ;;
        pending)   printf '%s\n' "$line" | grep -q fixed-pending-merge || continue ;;
      esac
      echo "$line"
    done
  done
  echo
done
