// @generated by tools/ir_schema/extract.py from tools/ir_schema/ir.loft
// via `loft --native --show-rust`.  DO NOT EDIT — regenerate.
// Copyright (c) 2026 Jurjen Stellingwerff
// SPDX-License-Identifier: LGPL-3.0-or-later
//
//! The store schema for the compiler IR (@PLN11 arc A): registers every
//! IR struct/enum as `Stores` type records so the IR can live in a store and
//! the schema-driven inspection layer (`Stores::show_json`) can walk it.
#![allow(
    clippy::too_many_lines,
    unused_variables,
    clippy::let_and_return,
    clippy::similar_names
)]

use crate::database::Stores;

/// Registered type numbers for the IR types, returned by
/// [`register_ir_schema`] so the typed accessor layer can bind to them.
#[derive(Clone, Copy, Debug)]
pub struct IrSchemaIds {
    /// `known_type` of the `DbContent` enum.
    pub db_content: u16,
    /// `known_type` of the `DbParts` enum.
    pub db_parts: u16,
    /// `known_type` of the `Node` enum.
    pub node: u16,
    /// `known_type` of the `TypeT` enum.
    pub type_t: u16,
    /// `known_type` of `AppliedImport`.
    pub applied_import: u16,
    /// `known_type` of `Attribute`.
    pub attribute: u16,
    /// `known_type` of `Block`.
    pub block: u16,
    /// `known_type` of `Bundle`.
    pub bundle: u16,
    /// `known_type` of `Data`.
    pub data: u16,
    /// `known_type` of `DbField`.
    pub db_field: u16,
    /// `known_type` of `DbType`.
    pub db_type: u16,
    /// `known_type` of `DcFloat`.
    pub dc_float: u16,
    /// `known_type` of `DcLong`.
    pub dc_long: u16,
    /// `known_type` of `DcSingle`.
    pub dc_single: u16,
    /// `known_type` of `DcStr`.
    pub dc_str: u16,
    /// `known_type` of `Definition`.
    pub definition: u16,
    /// `known_type` of `EnumPair`.
    pub enum_pair: u16,
    /// `known_type` of `Function`.
    pub function: u16,
    /// `known_type` of `IntegerSpec`.
    pub integer_spec: u16,
    /// `known_type` of `Key`.
    pub key: u16,
    /// `known_type` of `KeyField`.
    pub key_field: u16,
    /// `known_type` of `LinkedFieldGroup`.
    pub linked_field_group: u16,
    /// `known_type` of `NameNr`.
    pub name_nr: u16,
    /// `known_type` of `NameRef`.
    pub name_ref: u16,
    /// `known_type` of `NdBlock`.
    pub nd_block: u16,
    /// `known_type` of `NdBoolean`.
    pub nd_boolean: u16,
    /// `known_type` of `NdBreak`.
    pub nd_break: u16,
    /// `known_type` of `NdCall`.
    pub nd_call: u16,
    /// `known_type` of `NdCallRef`.
    pub nd_call_ref: u16,
    /// `known_type` of `NdContinue`.
    pub nd_continue: u16,
    /// `known_type` of `NdDrop`.
    pub nd_drop: u16,
    /// `known_type` of `NdEnum`.
    pub nd_enum: u16,
    /// `known_type` of `NdFloat`.
    pub nd_float: u16,
    /// `known_type` of `NdFnRef`.
    pub nd_fn_ref: u16,
    /// `known_type` of `NdFnRefDnr`.
    pub nd_fn_ref_dnr: u16,
    /// `known_type` of `NdIf`.
    pub nd_if: u16,
    /// `known_type` of `NdInsert`.
    pub nd_insert: u16,
    /// `known_type` of `NdInt`.
    pub nd_int: u16,
    /// `known_type` of `NdIter`.
    pub nd_iter: u16,
    /// `known_type` of `NdKeys`.
    pub nd_keys: u16,
    /// `known_type` of `NdLine`.
    pub nd_line: u16,
    /// `known_type` of `NdLong`.
    pub nd_long: u16,
    /// `known_type` of `NdLoop`.
    pub nd_loop: u16,
    /// `known_type` of `NdNull`.
    pub nd_null: u16,
    /// `known_type` of `NdParallel`.
    pub nd_parallel: u16,
    /// `known_type` of `NdRawExpr`.
    pub nd_raw_expr: u16,
    /// `known_type` of `NdReturn`.
    pub nd_return: u16,
    /// `known_type` of `NdSet`.
    pub nd_set: u16,
    /// `known_type` of `NdSingle`.
    pub nd_single: u16,
    /// `known_type` of `NdSpan`.
    pub nd_span: u16,
    /// `known_type` of `NdText`.
    pub nd_text: u16,
    /// `known_type` of `NdTuple`.
    pub nd_tuple: u16,
    /// `known_type` of `NdTupleGet`.
    pub nd_tuple_get: u16,
    /// `known_type` of `NdTuplePut`.
    pub nd_tuple_put: u16,
    /// `known_type` of `NdVar`.
    pub nd_var: u16,
    /// `known_type` of `NdYield`.
    pub nd_yield: u16,
    /// `known_type` of `Position`.
    pub position: u16,
    /// `known_type` of `PtArray`.
    pub pt_array: u16,
    /// `known_type` of `PtBase`.
    pub pt_base: u16,
    /// `known_type` of `PtByte`.
    pub pt_byte: u16,
    /// `known_type` of `PtChildRec`.
    pub pt_child_rec: u16,
    /// `known_type` of `PtDbRef`.
    pub pt_db_ref: u16,
    /// `known_type` of `PtEnum`.
    pub pt_enum: u16,
    /// `known_type` of `PtEnumValue`.
    pub pt_enum_value: u16,
    /// `known_type` of `PtHash`.
    pub pt_hash: u16,
    /// `known_type` of `PtIndex`.
    pub pt_index: u16,
    /// `known_type` of `PtInt`.
    pub pt_int: u16,
    /// `known_type` of `PtIntRaw`.
    pub pt_int_raw: u16,
    /// `known_type` of `PtOrdered`.
    pub pt_ordered: u16,
    /// `known_type` of `PtRadix`.
    pub pt_radix: u16,
    /// `known_type` of `PtShort`.
    pub pt_short: u16,
    /// `known_type` of `PtShortRaw`.
    pub pt_short_raw: u16,
    /// `known_type` of `PtSorted`.
    pub pt_sorted: u16,
    /// `known_type` of `PtStruct`.
    pub pt_struct: u16,
    /// `known_type` of `PtTrie`.
    pub pt_trie: u16,
    /// `known_type` of `PtVector`.
    pub pt_vector: u16,
    /// `known_type` of `SortKey`.
    pub sort_key: u16,
    /// `known_type` of `TyBoolean`.
    pub ty_boolean: u16,
    /// `known_type` of `TyCharacter`.
    pub ty_character: u16,
    /// `known_type` of `TyEnum`.
    pub ty_enum: u16,
    /// `known_type` of `TyFloat`.
    pub ty_float: u16,
    /// `known_type` of `TyFunction`.
    pub ty_function: u16,
    /// `known_type` of `TyHash`.
    pub ty_hash: u16,
    /// `known_type` of `TyIndex`.
    pub ty_index: u16,
    /// `known_type` of `TyInteger`.
    pub ty_integer: u16,
    /// `known_type` of `TyIterator`.
    pub ty_iterator: u16,
    /// `known_type` of `TyKeys`.
    pub ty_keys: u16,
    /// `known_type` of `TyNever`.
    pub ty_never: u16,
    /// `known_type` of `TyNull`.
    pub ty_null: u16,
    /// `known_type` of `TyOptional`.
    pub ty_optional: u16,
    /// `known_type` of `TyRadix`.
    pub ty_radix: u16,
    /// `known_type` of `TyRefVar`.
    pub ty_ref_var: u16,
    /// `known_type` of `TyReference`.
    pub ty_reference: u16,
    /// `known_type` of `TyRewritten`.
    pub ty_rewritten: u16,
    /// `known_type` of `TyRoutine`.
    pub ty_routine: u16,
    /// `known_type` of `TySingle`.
    pub ty_single: u16,
    /// `known_type` of `TySorted`.
    pub ty_sorted: u16,
    /// `known_type` of `TyText`.
    pub ty_text: u16,
    /// `known_type` of `TyTrie`.
    pub ty_trie: u16,
    /// `known_type` of `TyTuple`.
    pub ty_tuple: u16,
    /// `known_type` of `TyUnknown`.
    pub ty_unknown: u16,
    /// `known_type` of `TyVector`.
    pub ty_vector: u16,
    /// `known_type` of `TyVoid`.
    pub ty_void: u16,
    /// `known_type` of `UseName`.
    pub use_name: u16,
    /// `known_type` of `Variable`.
    pub variable: u16,
}

/// Register the full compiler-IR store schema into `db`.
/// Generated verbatim from the `--native` layout; register once per `Stores`.
#[must_use]
pub fn register_ir_schema(db: &mut Stores) -> IrSchemaIds {
    let t0: u16 = 0;
    let t1: u16 = 1;
    let t2: u16 = 2;
    let t3: u16 = 3;
    let t4: u16 = 4;
    let t5: u16 = 5;
    let t6: u16 = 6;
    let _ = (t0, t1, t2, t3, t4, t5, t6);
    let t7 = db.enumerate("TypeT");
    let t8 = db.enumerate("Node");
    let t9 = db.enumerate("DbContent");
    let t10 = db.enumerate("DbParts");
    let t11 = db.structure("Position", 0);
    let t12 = db.structure("Key", 0);
    let t13 = db.structure("SortKey", 0);
    let t14 = db.structure("NameRef", 0);
    let t15 = db.structure("NameNr", 0);
    let t16 = db.structure("IntegerSpec", 0);
    let t17 = db.structure("TyUnknown", 1);
    let t18 = db.structure("TyNull", 2);
    let t19 = db.structure("TyVoid", 3);
    let t20 = db.structure("TyNever", 4);
    let t21 = db.structure("TyInteger", 5);
    let t22 = db.structure("TyBoolean", 6);
    let t23 = db.structure("TyFloat", 7);
    let t24 = db.structure("TySingle", 8);
    let t25 = db.structure("TyCharacter", 9);
    let t26 = db.structure("TyText", 10);
    let t27 = db.structure("TyKeys", 11);
    let t28 = db.structure("TyEnum", 12);
    let t29 = db.structure("TyReference", 13);
    let t30 = db.structure("TyRefVar", 14);
    let t31 = db.structure("TyVector", 15);
    let t32 = db.structure("TyRoutine", 16);
    let t33 = db.structure("TyIterator", 17);
    let t34 = db.structure("TySorted", 18);
    let t35 = db.structure("TyIndex", 19);
    let t36 = db.structure("TyRadix", 20);
    let t37 = db.structure("TyHash", 21);
    let t38 = db.structure("TyFunction", 22);
    let t39 = db.structure("TyRewritten", 23);
    let t40 = db.structure("TyTuple", 24);
    let t41 = db.structure("TyOptional", 25);
    let t42 = db.structure("TyTrie", 26);
    let t43 = db.structure("NdNull", 1);
    let t44 = db.structure("NdLine", 2);
    let t45 = db.structure("NdSpan", 3);
    let t46 = db.structure("NdInt", 4);
    let t47 = db.structure("NdEnum", 5);
    let t48 = db.structure("NdBoolean", 6);
    let t49 = db.structure("NdFloat", 7);
    let t50 = db.structure("NdLong", 8);
    let t51 = db.structure("NdSingle", 9);
    let t52 = db.structure("NdText", 10);
    let t53 = db.structure("NdCall", 11);
    let t54 = db.structure("NdCallRef", 12);
    let t55 = db.structure("NdBlock", 13);
    let t56 = db.structure("Block", 0);
    let t57 = db.structure("NdInsert", 14);
    let t58 = db.structure("NdVar", 15);
    let t59 = db.structure("NdSet", 16);
    let t60 = db.structure("NdReturn", 17);
    let t61 = db.structure("NdBreak", 18);
    let t62 = db.structure("NdContinue", 19);
    let t63 = db.structure("NdIf", 20);
    let t64 = db.structure("NdLoop", 21);
    let t65 = db.structure("NdDrop", 22);
    let t66 = db.structure("NdIter", 23);
    let t67 = db.structure("NdKeys", 24);
    let t68 = db.structure("NdTuple", 25);
    let t69 = db.structure("NdTupleGet", 26);
    let t70 = db.structure("NdTuplePut", 27);
    let t71 = db.structure("NdYield", 28);
    let t72 = db.structure("NdFnRef", 29);
    let t73 = db.structure("NdFnRefDnr", 30);
    let t74 = db.structure("NdParallel", 31);
    let t75 = db.structure("NdRawExpr", 32);
    let t76 = db.structure("Attribute", 0);
    let t77 = db.structure("Variable", 0);
    let t78 = db.structure("Function", 0);
    let t79 = db.structure("LinkedFieldGroup", 0);
    let t80 = db.structure("Definition", 0);
    let t81 = db.structure("AppliedImport", 0);
    let t82 = db.structure("UseName", 0);
    let t83 = db.structure("Data", 0);
    let t84 = db.structure("DcLong", 1);
    let t85 = db.structure("DcFloat", 2);
    let t86 = db.structure("DcSingle", 3);
    let t87 = db.structure("DcStr", 4);
    let t88 = db.structure("DbField", 0);
    let t89 = db.structure("EnumPair", 0);
    let t90 = db.structure("KeyField", 0);
    let t91 = db.structure("PtBase", 1);
    let t92 = db.structure("PtStruct", 2);
    let t93 = db.structure("PtEnum", 3);
    let t94 = db.structure("PtEnumValue", 4);
    let t95 = db.structure("PtByte", 5);
    let t96 = db.structure("PtShort", 6);
    let t97 = db.structure("PtInt", 7);
    let t98 = db.structure("PtShortRaw", 8);
    let t99 = db.structure("PtVector", 9);
    let t100 = db.structure("PtArray", 10);
    let t101 = db.structure("PtSorted", 11);
    let t102 = db.structure("PtOrdered", 12);
    let t103 = db.structure("PtHash", 13);
    let t104 = db.structure("PtIndex", 14);
    let t105 = db.structure("PtRadix", 15);
    let t106 = db.structure("PtDbRef", 16);
    let t107 = db.structure("PtChildRec", 17);
    let t108 = db.structure("PtTrie", 18);
    let t109 = db.structure("PtIntRaw", 19);
    let t110 = db.structure("DbType", 0);
    let t111 = db.structure("Bundle", 0);
    db.field(t11, "file", t5);
    db.field(t11, "line", 0);
    db.field(t11, "pos", 0);
    db.field(t12, "type_nr", 0);
    db.field(t12, "position", 0);
    db.field(t12, "start", 0);
    db.field(t13, "name", t5);
    db.field(t13, "asc", t4);
    db.field(t14, "name", t5);
    db.field(t15, "name", t5);
    db.field(t15, "nr", 0);
    db.field(t16, "min", 0);
    db.field(t16, "max", 0);
    db.field(t16, "not_null", t4);
    db.field(t16, "forced_size", 0);
    let byte_enum = db.byte(0, false);
    db.field(t17, "enum", byte_enum);
    db.field(t17, "n", 0);
    let byte_enum = db.byte(0, false);
    db.field(t18, "enum", byte_enum);
    let byte_enum = db.byte(0, false);
    db.field(t19, "enum", byte_enum);
    let byte_enum = db.byte(0, false);
    db.field(t20, "enum", byte_enum);
    let byte_enum = db.byte(0, false);
    db.field(t21, "enum", byte_enum);
    db.field(t21, "spec", t16);
    let byte_enum = db.byte(0, false);
    db.field(t22, "enum", byte_enum);
    let byte_enum = db.byte(0, false);
    db.field(t23, "enum", byte_enum);
    let byte_enum = db.byte(0, false);
    db.field(t24, "enum", byte_enum);
    let byte_enum = db.byte(0, false);
    db.field(t25, "enum", byte_enum);
    let byte_enum = db.byte(0, false);
    db.field(t26, "enum", byte_enum);
    let vec_dep = db.vector(t0);
    db.field(t26, "dep", vec_dep);
    let byte_enum = db.byte(0, false);
    db.field(t27, "enum", byte_enum);
    let byte_enum = db.byte(0, false);
    db.field(t28, "enum", byte_enum);
    db.field(t28, "n", 0);
    db.field(t28, "is_ref", t4);
    let vec_dep = db.vector(t0);
    db.field(t28, "dep", vec_dep);
    let byte_enum = db.byte(0, false);
    db.field(t29, "enum", byte_enum);
    db.field(t29, "n", 0);
    let vec_dep = db.vector(t0);
    db.field(t29, "dep", vec_dep);
    let byte_enum = db.byte(0, false);
    db.field(t30, "enum", byte_enum);
    let vec_inner = db.vector(t7);
    db.field(t30, "inner", vec_inner);
    let t112 = db.vector(t7);
    let _ = t112; // may be unused
    let byte_enum = db.byte(0, false);
    db.field(t31, "enum", byte_enum);
    let vec_inner = db.vector(t7);
    db.field(t31, "inner", vec_inner);
    let vec_dep = db.vector(t0);
    db.field(t31, "dep", vec_dep);
    let byte_enum = db.byte(0, false);
    db.field(t32, "enum", byte_enum);
    db.field(t32, "n", 0);
    let byte_enum = db.byte(0, false);
    db.field(t33, "enum", byte_enum);
    let vec_step = db.vector(t7);
    db.field(t33, "step", vec_step);
    let vec_inner = db.vector(t7);
    db.field(t33, "inner", vec_inner);
    let byte_enum = db.byte(0, false);
    db.field(t34, "enum", byte_enum);
    db.field(t34, "n", 0);
    let vec_keys = db.vector(t13);
    db.field(t34, "keys", vec_keys);
    let vec_dep = db.vector(t0);
    db.field(t34, "dep", vec_dep);
    let t113 = db.vector(t13);
    let _ = t113; // may be unused
    let byte_enum = db.byte(0, false);
    db.field(t35, "enum", byte_enum);
    db.field(t35, "n", 0);
    let vec_keys = db.vector(t13);
    db.field(t35, "keys", vec_keys);
    let vec_dep = db.vector(t0);
    db.field(t35, "dep", vec_dep);
    let byte_enum = db.byte(0, false);
    db.field(t36, "enum", byte_enum);
    db.field(t36, "n", 0);
    let vec_names = db.vector(t14);
    db.field(t36, "names", vec_names);
    let vec_dep = db.vector(t0);
    db.field(t36, "dep", vec_dep);
    let t114 = db.vector(t14);
    let _ = t114; // may be unused
    let byte_enum = db.byte(0, false);
    db.field(t37, "enum", byte_enum);
    db.field(t37, "n", 0);
    let vec_names = db.vector(t14);
    db.field(t37, "names", vec_names);
    let vec_dep = db.vector(t0);
    db.field(t37, "dep", vec_dep);
    let byte_enum = db.byte(0, false);
    db.field(t38, "enum", byte_enum);
    let vec_args = db.vector(t7);
    db.field(t38, "args", vec_args);
    let vec_result = db.vector(t7);
    db.field(t38, "result", vec_result);
    let vec_dep = db.vector(t0);
    db.field(t38, "dep", vec_dep);
    let byte_enum = db.byte(0, false);
    db.field(t39, "enum", byte_enum);
    let vec_inner = db.vector(t7);
    db.field(t39, "inner", vec_inner);
    let byte_enum = db.byte(0, false);
    db.field(t40, "enum", byte_enum);
    let vec_elems = db.vector(t7);
    db.field(t40, "elems", vec_elems);
    let byte_enum = db.byte(0, false);
    db.field(t41, "enum", byte_enum);
    let vec_inner = db.vector(t7);
    db.field(t41, "inner", vec_inner);
    let byte_enum = db.byte(0, false);
    db.field(t42, "enum", byte_enum);
    db.field(t42, "n", 0);
    db.field(t42, "key", t5);
    let vec_dep = db.vector(t0);
    db.field(t42, "dep", vec_dep);
    let byte_enum = db.byte(0, false);
    db.field(t43, "enum", byte_enum);
    let byte_enum = db.byte(0, false);
    db.field(t44, "enum", byte_enum);
    db.field(t44, "n", 0);
    let byte_enum = db.byte(0, false);
    db.field(t45, "enum", byte_enum);
    db.field(t45, "pos", t11);
    let vec_inner = db.vector(t8);
    db.field(t45, "inner", vec_inner);
    let t115 = db.vector(t8);
    let _ = t115; // may be unused
    let byte_enum = db.byte(0, false);
    db.field(t46, "enum", byte_enum);
    db.field(t46, "n", 0);
    let byte_enum = db.byte(0, false);
    db.field(t47, "enum", byte_enum);
    db.field(t47, "ord", 0);
    db.field(t47, "tp", 0);
    let byte_enum = db.byte(0, false);
    db.field(t48, "enum", byte_enum);
    db.field(t48, "b", t4);
    let byte_enum = db.byte(0, false);
    db.field(t49, "enum", byte_enum);
    db.field(t49, "f", t3);
    let byte_enum = db.byte(0, false);
    db.field(t50, "enum", byte_enum);
    db.field(t50, "n", 0);
    let byte_enum = db.byte(0, false);
    db.field(t51, "enum", byte_enum);
    db.field(t51, "f", t2);
    let byte_enum = db.byte(0, false);
    db.field(t52, "enum", byte_enum);
    db.field(t52, "s", t5);
    let byte_enum = db.byte(0, false);
    db.field(t53, "enum", byte_enum);
    db.field(t53, "def_nr", 0);
    let vec_args = db.vector(t8);
    db.field(t53, "args", vec_args);
    let byte_enum = db.byte(0, false);
    db.field(t54, "enum", byte_enum);
    db.field(t54, "var", 0);
    let vec_args = db.vector(t8);
    db.field(t54, "args", vec_args);
    let byte_enum = db.byte(0, false);
    db.field(t55, "enum", byte_enum);
    db.field(t56, "name", t5);
    let vec_operators = db.vector(t8);
    db.field(t56, "operators", vec_operators);
    let vec_result = db.vector(t7);
    db.field(t56, "result", vec_result);
    db.field(t56, "scope", 0);
    db.field(t56, "var_size", 0);
    let vec_block = db.vector(t56);
    db.field(t55, "block", vec_block);
    let t116 = db.vector(t56);
    let _ = t116; // may be unused
    let byte_enum = db.byte(0, false);
    db.field(t57, "enum", byte_enum);
    let vec_items = db.vector(t8);
    db.field(t57, "items", vec_items);
    let byte_enum = db.byte(0, false);
    db.field(t58, "enum", byte_enum);
    db.field(t58, "n", 0);
    let byte_enum = db.byte(0, false);
    db.field(t59, "enum", byte_enum);
    db.field(t59, "var", 0);
    let vec_inner = db.vector(t8);
    db.field(t59, "inner", vec_inner);
    let byte_enum = db.byte(0, false);
    db.field(t60, "enum", byte_enum);
    let vec_inner = db.vector(t8);
    db.field(t60, "inner", vec_inner);
    let byte_enum = db.byte(0, false);
    db.field(t61, "enum", byte_enum);
    db.field(t61, "n", 0);
    let byte_enum = db.byte(0, false);
    db.field(t62, "enum", byte_enum);
    db.field(t62, "n", 0);
    let byte_enum = db.byte(0, false);
    db.field(t63, "enum", byte_enum);
    let vec_cond = db.vector(t8);
    db.field(t63, "cond", vec_cond);
    let vec_t = db.vector(t8);
    db.field(t63, "t", vec_t);
    let vec_f = db.vector(t8);
    db.field(t63, "f", vec_f);
    let byte_enum = db.byte(0, false);
    db.field(t64, "enum", byte_enum);
    let vec_block = db.vector(t56);
    db.field(t64, "block", vec_block);
    let byte_enum = db.byte(0, false);
    db.field(t65, "enum", byte_enum);
    let vec_inner = db.vector(t8);
    db.field(t65, "inner", vec_inner);
    let byte_enum = db.byte(0, false);
    db.field(t66, "enum", byte_enum);
    db.field(t66, "var", 0);
    let vec_create = db.vector(t8);
    db.field(t66, "create", vec_create);
    let vec_next = db.vector(t8);
    db.field(t66, "next", vec_next);
    let vec_init = db.vector(t8);
    db.field(t66, "init", vec_init);
    let byte_enum = db.byte(0, false);
    db.field(t67, "enum", byte_enum);
    let vec_keys = db.vector(t12);
    db.field(t67, "keys", vec_keys);
    let t117 = db.vector(t12);
    let _ = t117; // may be unused
    let byte_enum = db.byte(0, false);
    db.field(t68, "enum", byte_enum);
    let vec_items = db.vector(t8);
    db.field(t68, "items", vec_items);
    let byte_enum = db.byte(0, false);
    db.field(t69, "enum", byte_enum);
    db.field(t69, "var", 0);
    db.field(t69, "idx", 0);
    let byte_enum = db.byte(0, false);
    db.field(t70, "enum", byte_enum);
    db.field(t70, "var", 0);
    db.field(t70, "idx", 0);
    let vec_inner = db.vector(t8);
    db.field(t70, "inner", vec_inner);
    let byte_enum = db.byte(0, false);
    db.field(t71, "enum", byte_enum);
    let vec_inner = db.vector(t8);
    db.field(t71, "inner", vec_inner);
    let byte_enum = db.byte(0, false);
    db.field(t72, "enum", byte_enum);
    db.field(t72, "def_nr", 0);
    db.field(t72, "var", 0);
    let vec_t = db.vector(t7);
    db.field(t72, "t", vec_t);
    let byte_enum = db.byte(0, false);
    db.field(t73, "enum", byte_enum);
    db.field(t73, "n", 0);
    let byte_enum = db.byte(0, false);
    db.field(t74, "enum", byte_enum);
    let vec_arms = db.vector(t8);
    db.field(t74, "arms", vec_arms);
    let byte_enum = db.byte(0, false);
    db.field(t75, "enum", byte_enum);
    db.field(t75, "s", t5);
    db.field(t76, "name", t5);
    let vec_typedef = db.vector(t7);
    db.field(t76, "typedef", vec_typedef);
    db.field(t76, "mutable", t4);
    db.field(t76, "constant", t4);
    db.field(t76, "init", t4);
    db.field(t76, "nullable", t4);
    db.field(t76, "primary", t4);
    db.field(t76, "hidden", t4);
    db.field(t76, "const_field", t4);
    let vec_value = db.vector(t8);
    db.field(t76, "value", vec_value);
    let vec_check = db.vector(t8);
    db.field(t76, "check", vec_check);
    let vec_check_message = db.vector(t8);
    db.field(t76, "check_message", vec_check_message);
    db.field(t76, "alias_d_nr", 0);
    db.field(t76, "assigned_lambda_d_nr", 0);
    db.field(t76, "links", t5);
    db.field(t77, "name", t5);
    let vec_type_def = db.vector(t7);
    db.field(t77, "type_def", vec_type_def);
    db.field(t77, "stack_pos", 0);
    db.field(t77, "uses", 0);
    db.field(t77, "argument", t4);
    db.field(t77, "stack_allocated", t4);
    db.field(t77, "skip_free", t4);
    db.field(t77, "captured", t4);
    db.field(t77, "caller_hidden_buf", t4);
    db.field(t77, "view_elided", t4);
    db.field(t77, "owner_witness", 0);
    db.field(t78, "name", t5);
    db.field(t78, "file", t5);
    let vec_variables = db.vector(t77);
    db.field(t78, "variables", vec_variables);
    let vec_names = db.vector(t15);
    db.field(t78, "names", vec_names);
    let vec_inline_refs = db.vector(t0);
    db.field(t78, "inline_refs", vec_inline_refs);
    let t118 = db.vector(t77);
    let _ = t118; // may be unused
    let t119 = db.vector(t15);
    let _ = t119; // may be unused
    db.field(t79, "kind", 0);
    db.field(t79, "instance", 0);
    let vec_field_indices = db.vector(t0);
    db.field(t79, "field_indices", vec_field_indices);
    db.field(t79, "alignment", 0);
    db.field(t79, "size", 0);
    db.field(t80, "name", t5);
    db.field(t80, "source", 0);
    db.field(t80, "def_type", 0);
    db.field(t80, "parent", 0);
    db.field(t80, "position", t11);
    let vec_attributes = db.vector(t76);
    db.field(t80, "attributes", vec_attributes);
    let vec_code = db.vector(t8);
    db.field(t80, "code", vec_code);
    let vec_returned = db.vector(t7);
    db.field(t80, "returned", vec_returned);
    db.field(t80, "returned_not_null", t4);
    db.field(t80, "rust", t5);
    db.field(t80, "native", t5);
    db.field(t80, "op_code", 0);
    db.field(t80, "known_type", 0);
    db.field(t80, "variables", t78);
    db.field(t80, "pub_visible", t4);
    db.field(t80, "null_safe", t4);
    db.field(t80, "closure_record", 0);
    let vec_mutated_captures = db.vector(t14);
    db.field(t80, "mutated_captures", vec_mutated_captures);
    let vec_scalars_to_box = db.vector(t14);
    db.field(t80, "scalars_to_box", vec_scalars_to_box);
    let vec_bounds = db.vector(t0);
    db.field(t80, "bounds", vec_bounds);
    db.field(t80, "forced_size", 0);
    db.field(t80, "purity", 0);
    let vec_field_groups = db.vector(t79);
    db.field(t80, "field_groups", vec_field_groups);
    db.field(t80, "synthetic", t5);
    db.field(t80, "cap", t5);
    db.field(t80, "superseded", t5);
    db.field(t80, "c_symbol", t5);
    db.field(t80, "c_sig", t5);
    let t120 = db.vector(t76);
    let _ = t120; // may be unused
    let t121 = db.vector(t79);
    let _ = t121; // may be unused
    db.field(t81, "lib_source", 0);
    db.field(t81, "into_source", 0);
    db.field(t81, "name", t5);
    db.field(t81, "bind", t5);
    db.field(t82, "name", t5);
    db.field(t82, "source", 0);
    let vec_definitions = db.vector(t80);
    db.field(t83, "definitions", vec_definitions);
    db.field(t83, "source", 0);
    let vec_imports = db.vector(t81);
    db.field(t83, "imports", vec_imports);
    let vec_use_names = db.vector(t82);
    db.field(t83, "use_names", vec_use_names);
    let t122 = db.vector(t80);
    let _ = t122; // may be unused
    let t123 = db.vector(t81);
    let _ = t123; // may be unused
    let t124 = db.vector(t82);
    let _ = t124; // may be unused
    let byte_enum = db.byte(0, false);
    db.field(t84, "enum", byte_enum);
    db.field(t84, "v", 0);
    let byte_enum = db.byte(0, false);
    db.field(t85, "enum", byte_enum);
    db.field(t85, "v", t3);
    let byte_enum = db.byte(0, false);
    db.field(t86, "enum", byte_enum);
    db.field(t86, "v", t2);
    let byte_enum = db.byte(0, false);
    db.field(t87, "enum", byte_enum);
    db.field(t87, "v", t5);
    db.field(t88, "name", t5);
    db.field(t88, "content", 0);
    db.field(t88, "position", 0);
    let vec_default = db.vector(t9);
    db.field(t88, "default", vec_default);
    let vec_other_indexes = db.vector(t0);
    db.field(t88, "other_indexes", vec_other_indexes);
    db.field(t88, "nullable", t4);
    let t125 = db.vector(t9);
    let _ = t125; // may be unused
    db.field(t89, "nr", 0);
    db.field(t89, "name", t5);
    db.field(t90, "nr", 0);
    db.field(t90, "asc", t4);
    let byte_enum = db.byte(0, false);
    db.field(t91, "enum", byte_enum);
    let byte_enum = db.byte(0, false);
    db.field(t92, "enum", byte_enum);
    let vec_fields = db.vector(t88);
    db.field(t92, "fields", vec_fields);
    let t126 = db.vector(t88);
    let _ = t126; // may be unused
    let byte_enum = db.byte(0, false);
    db.field(t93, "enum", byte_enum);
    let vec_values = db.vector(t89);
    db.field(t93, "values", vec_values);
    let t127 = db.vector(t89);
    let _ = t127; // may be unused
    let byte_enum = db.byte(0, false);
    db.field(t94, "enum", byte_enum);
    db.field(t94, "value", 0);
    let vec_fields = db.vector(t88);
    db.field(t94, "fields", vec_fields);
    let byte_enum = db.byte(0, false);
    db.field(t95, "enum", byte_enum);
    db.field(t95, "start", 0);
    db.field(t95, "nullable", t4);
    let byte_enum = db.byte(0, false);
    db.field(t96, "enum", byte_enum);
    db.field(t96, "start", 0);
    db.field(t96, "nullable", t4);
    let byte_enum = db.byte(0, false);
    db.field(t97, "enum", byte_enum);
    db.field(t97, "start", 0);
    db.field(t97, "nullable", t4);
    let byte_enum = db.byte(0, false);
    db.field(t98, "enum", byte_enum);
    db.field(t98, "start", 0);
    db.field(t98, "nullable", t4);
    let byte_enum = db.byte(0, false);
    db.field(t99, "enum", byte_enum);
    db.field(t99, "content", 0);
    let byte_enum = db.byte(0, false);
    db.field(t100, "enum", byte_enum);
    db.field(t100, "content", 0);
    let byte_enum = db.byte(0, false);
    db.field(t101, "enum", byte_enum);
    db.field(t101, "content", 0);
    let vec_keys = db.vector(t90);
    db.field(t101, "keys", vec_keys);
    let t128 = db.vector(t90);
    let _ = t128; // may be unused
    let byte_enum = db.byte(0, false);
    db.field(t102, "enum", byte_enum);
    db.field(t102, "content", 0);
    let vec_keys = db.vector(t90);
    db.field(t102, "keys", vec_keys);
    let byte_enum = db.byte(0, false);
    db.field(t103, "enum", byte_enum);
    db.field(t103, "content", 0);
    let vec_fields = db.vector(t0);
    db.field(t103, "fields", vec_fields);
    let byte_enum = db.byte(0, false);
    db.field(t104, "enum", byte_enum);
    db.field(t104, "content", 0);
    let vec_keys = db.vector(t90);
    db.field(t104, "keys", vec_keys);
    db.field(t104, "left", 0);
    let byte_enum = db.byte(0, false);
    db.field(t105, "enum", byte_enum);
    db.field(t105, "content", 0);
    let vec_fields = db.vector(t0);
    db.field(t105, "fields", vec_fields);
    let byte_enum = db.byte(0, false);
    db.field(t106, "enum", byte_enum);
    let byte_enum = db.byte(0, false);
    db.field(t107, "enum", byte_enum);
    db.field(t107, "content", 0);
    let byte_enum = db.byte(0, false);
    db.field(t108, "enum", byte_enum);
    db.field(t108, "content", 0);
    db.field(t108, "key", 0);
    let byte_enum = db.byte(0, false);
    db.field(t109, "enum", byte_enum);
    db.field(t109, "start", 0);
    db.field(t109, "nullable", t4);
    db.field(t110, "name", t5);
    let vec_parts = db.vector(t10);
    db.field(t110, "parts", vec_parts);
    let vec_keys = db.vector(t12);
    db.field(t110, "keys", vec_keys);
    db.field(t110, "complex", t4);
    db.field(t110, "linked", t4);
    db.field(t110, "size", 0);
    db.field(t110, "align", 0);
    let vec_field_groups = db.vector(t79);
    db.field(t110, "field_groups", vec_field_groups);
    let t129 = db.vector(t10);
    let _ = t129; // may be unused
    db.field(t111, "data", t83);
    let vec_types = db.vector(t110);
    db.field(t111, "types", vec_types);
    let t130 = db.vector(t110);
    let _ = t130; // may be unused
    let vec_vector = db.vector(t7);
    let vec_vector = db.vector(t13);
    let vec_vector = db.vector(t14);
    let vec_vector = db.vector(t8);
    let vec_vector = db.vector(t56);
    let vec_vector = db.vector(t12);
    let vec_vector = db.vector(t77);
    let vec_vector = db.vector(t15);
    let vec_vector = db.vector(t76);
    let vec_vector = db.vector(t79);
    let vec_vector = db.vector(t80);
    let vec_vector = db.vector(t81);
    let vec_vector = db.vector(t82);
    let vec_vector = db.vector(t9);
    let vec_vector = db.vector(t88);
    let vec_vector = db.vector(t89);
    let vec_vector = db.vector(t90);
    let vec_vector = db.vector(t10);
    let vec_vector = db.vector(t110);
    db.value(t7, "TyUnknown", t17);
    db.value(t7, "TyNull", t18);
    db.value(t7, "TyVoid", t19);
    db.value(t7, "TyNever", t20);
    db.value(t7, "TyInteger", t21);
    db.value(t7, "TyBoolean", t22);
    db.value(t7, "TyFloat", t23);
    db.value(t7, "TySingle", t24);
    db.value(t7, "TyCharacter", t25);
    db.value(t7, "TyText", t26);
    db.value(t7, "TyKeys", t27);
    db.value(t7, "TyEnum", t28);
    db.value(t7, "TyReference", t29);
    db.value(t7, "TyRefVar", t30);
    db.value(t7, "TyVector", t31);
    db.value(t7, "TyRoutine", t32);
    db.value(t7, "TyIterator", t33);
    db.value(t7, "TySorted", t34);
    db.value(t7, "TyIndex", t35);
    db.value(t7, "TyRadix", t36);
    db.value(t7, "TyHash", t37);
    db.value(t7, "TyFunction", t38);
    db.value(t7, "TyRewritten", t39);
    db.value(t7, "TyTuple", t40);
    db.value(t7, "TyOptional", t41);
    db.value(t7, "TyTrie", t42);
    db.value(t8, "NdNull", t43);
    db.value(t8, "NdLine", t44);
    db.value(t8, "NdSpan", t45);
    db.value(t8, "NdInt", t46);
    db.value(t8, "NdEnum", t47);
    db.value(t8, "NdBoolean", t48);
    db.value(t8, "NdFloat", t49);
    db.value(t8, "NdLong", t50);
    db.value(t8, "NdSingle", t51);
    db.value(t8, "NdText", t52);
    db.value(t8, "NdCall", t53);
    db.value(t8, "NdCallRef", t54);
    db.value(t8, "NdBlock", t55);
    db.value(t8, "NdInsert", t57);
    db.value(t8, "NdVar", t58);
    db.value(t8, "NdSet", t59);
    db.value(t8, "NdReturn", t60);
    db.value(t8, "NdBreak", t61);
    db.value(t8, "NdContinue", t62);
    db.value(t8, "NdIf", t63);
    db.value(t8, "NdLoop", t64);
    db.value(t8, "NdDrop", t65);
    db.value(t8, "NdIter", t66);
    db.value(t8, "NdKeys", t67);
    db.value(t8, "NdTuple", t68);
    db.value(t8, "NdTupleGet", t69);
    db.value(t8, "NdTuplePut", t70);
    db.value(t8, "NdYield", t71);
    db.value(t8, "NdFnRef", t72);
    db.value(t8, "NdFnRefDnr", t73);
    db.value(t8, "NdParallel", t74);
    db.value(t8, "NdRawExpr", t75);
    db.value(t9, "DcLong", t84);
    db.value(t9, "DcFloat", t85);
    db.value(t9, "DcSingle", t86);
    db.value(t9, "DcStr", t87);
    db.value(t10, "PtBase", t91);
    db.value(t10, "PtStruct", t92);
    db.value(t10, "PtEnum", t93);
    db.value(t10, "PtEnumValue", t94);
    db.value(t10, "PtByte", t95);
    db.value(t10, "PtShort", t96);
    db.value(t10, "PtInt", t97);
    db.value(t10, "PtShortRaw", t98);
    db.value(t10, "PtVector", t99);
    db.value(t10, "PtArray", t100);
    db.value(t10, "PtSorted", t101);
    db.value(t10, "PtOrdered", t102);
    db.value(t10, "PtHash", t103);
    db.value(t10, "PtIndex", t104);
    db.value(t10, "PtRadix", t105);
    db.value(t10, "PtDbRef", t106);
    db.value(t10, "PtChildRec", t107);
    db.value(t10, "PtTrie", t108);
    db.value(t10, "PtIntRaw", t109);
    db.finish();
    IrSchemaIds {
        db_content: t9,
        db_parts: t10,
        node: t8,
        type_t: t7,
        applied_import: t81,
        attribute: t76,
        block: t56,
        bundle: t111,
        data: t83,
        db_field: t88,
        db_type: t110,
        dc_float: t85,
        dc_long: t84,
        dc_single: t86,
        dc_str: t87,
        definition: t80,
        enum_pair: t89,
        function: t78,
        integer_spec: t16,
        key: t12,
        key_field: t90,
        linked_field_group: t79,
        name_nr: t15,
        name_ref: t14,
        nd_block: t55,
        nd_boolean: t48,
        nd_break: t61,
        nd_call: t53,
        nd_call_ref: t54,
        nd_continue: t62,
        nd_drop: t65,
        nd_enum: t47,
        nd_float: t49,
        nd_fn_ref: t72,
        nd_fn_ref_dnr: t73,
        nd_if: t63,
        nd_insert: t57,
        nd_int: t46,
        nd_iter: t66,
        nd_keys: t67,
        nd_line: t44,
        nd_long: t50,
        nd_loop: t64,
        nd_null: t43,
        nd_parallel: t74,
        nd_raw_expr: t75,
        nd_return: t60,
        nd_set: t59,
        nd_single: t51,
        nd_span: t45,
        nd_text: t52,
        nd_tuple: t68,
        nd_tuple_get: t69,
        nd_tuple_put: t70,
        nd_var: t58,
        nd_yield: t71,
        position: t11,
        pt_array: t100,
        pt_base: t91,
        pt_byte: t95,
        pt_child_rec: t107,
        pt_db_ref: t106,
        pt_enum: t93,
        pt_enum_value: t94,
        pt_hash: t103,
        pt_index: t104,
        pt_int: t97,
        pt_int_raw: t109,
        pt_ordered: t102,
        pt_radix: t105,
        pt_short: t96,
        pt_short_raw: t98,
        pt_sorted: t101,
        pt_struct: t92,
        pt_trie: t108,
        pt_vector: t99,
        sort_key: t13,
        ty_boolean: t22,
        ty_character: t25,
        ty_enum: t28,
        ty_float: t23,
        ty_function: t38,
        ty_hash: t37,
        ty_index: t35,
        ty_integer: t21,
        ty_iterator: t33,
        ty_keys: t27,
        ty_never: t20,
        ty_null: t18,
        ty_optional: t41,
        ty_radix: t36,
        ty_ref_var: t30,
        ty_reference: t29,
        ty_rewritten: t39,
        ty_routine: t32,
        ty_single: t24,
        ty_sorted: t34,
        ty_text: t26,
        ty_trie: t42,
        ty_tuple: t40,
        ty_unknown: t17,
        ty_vector: t31,
        ty_void: t19,
        use_name: t82,
        variable: t77,
    }
}
