// Copyright (c) 2026 Jurjen Stellingwerff
// SPDX-License-Identifier: LGPL-3.0-or-later
// @I77 — Registry / manifest / lockfile resolution

// Included by BOTH the library crate (where install.rs uses every fn)
// AND the binary crate (where parser/mod.rs::probe_registry_installed
// only reads).  `allow(dead_code)` silences the binary's view; in the
// lib the attribute is a no-op because every symbol IS used.
#![allow(dead_code)]

//! `loft.lock` — reproducible-build lock file for the package registry.
//!
//! PKG.REG R2 (PKG.7 in PACKAGES.md).  Auto-generated by `loft install`
//! / `loft update`; consumed by every subsequent `loft` invocation that
//! parses `loft.toml::[dependencies]`.  Pins each transitive dep to a
//! specific version + URL + SHA-256 so identical inputs produce
//! identical builds across machines / CI / collaborators.
//!
//! Format (TOML, ASCII-only values today):
//!
//! ```toml
//! # Auto-generated by loft — do not edit by hand.
//! # Run `loft install` to update.
//! schema_version = 1
//!
//! [[package]]
//! name = "crypto"
//! version = "0.1.0"
//! url = "https://github.com/loft-lang/loft-crypto/releases/download/v0.1.0/crypto-0.1.0.tar.gz"
//! sha256 = "abc123…"
//! source = "registry"
//!
//! [[package]]
//! name = "web"
//! version = "0.1.0"
//! url = "…"
//! sha256 = "…"
//! source = "registry"
//! deps = ["crypto"]
//! ```
//!
//! The reader is a minimal line scanner mirroring `src/manifest.rs` —
//! no TOML crate dependency (the format is constrained enough that a
//! 50-line scanner covers everything we emit).  The writer is the
//! authoritative emitter; everything in the file came from the writer.
//!
//! Source kinds (`source = "<kind>"`):
//!
//! - `registry` — the dep was resolved against `registry.json` and
//!   downloaded as a tarball.  This is the only kind today.
//! - Future: `git`, `path` for local overrides; the reader silently
//!   preserves unknown source kinds so an older loft binary doesn't
//!   corrupt a newer-format lockfile by rewriting it.

use std::fs;
use std::io;
use std::path::Path;

/// Current schema version emitted by the writer.  Bump on incompatible
/// changes; the reader rejects unknown major versions to prevent
/// silent corruption.
pub const SCHEMA_VERSION: u32 = 1;

/// Parsed `loft.lock` file.  Mirrors the TOML structure: a top-level
/// `schema_version` plus an array of `[[package]]` tables.
#[derive(Debug, Default, Clone, PartialEq, Eq)]
pub struct LockFile {
    pub schema_version: u32,
    pub packages: Vec<LockedPackage>,
}

/// One resolved package + version pin.
#[derive(Debug, Default, Clone, PartialEq, Eq)]
pub struct LockedPackage {
    /// Package name (`crypto`, `web`, …).
    pub name: String,
    /// Resolved semver (`0.1.0`).
    pub version: String,
    /// Download URL the tarball came from.  Recorded so a re-install
    /// produces byte-identical artefacts even if the registry index
    /// later updates the URL (mirror rotation, etc.).
    pub url: String,
    /// Lowercase hex SHA-256 of the tarball — re-verified on every
    /// install / re-extract.  Mismatch is a hard failure.
    pub sha256: String,
    /// Source kind: `"registry"`, future `"git"` / `"path"`.
    /// Defaults to `"registry"` when missing for backward compat with
    /// hand-written lockfiles.
    pub source: String,
    /// Names of other locked packages this one depends on.  Used by
    /// `loft install` to validate that the lockfile is internally
    /// consistent (every name in `deps` resolves to a `[[package]]`
    /// row).
    pub deps: Vec<String>,
}

/// One package `loft update` has to resolve, and what the lock currently
/// says about it.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct UpdateTarget {
    /// Package name.
    pub name: String,
    /// The version pinned in `loft.lock`, or `None` when `loft.toml` declares
    /// the dependency and the lock has no entry for it yet.  `None` is the
    /// case loft#830 was about: such a package needs ADDING, and a resolver
    /// that starts from the lock never sees it.
    pub locked: Option<String>,
}

/// The packages `loft update` must consider: every entry in `lock`, plus every
/// dependency `manifest_deps` DECLARES that the lock does not name.
///
/// Walking the lock alone is what made `loft update` skip a freshly declared
/// dependency and then report `all N packages up-to-date`, counting the lock
/// while the manifest asked for more (loft#830).  The lockfile is meant to
/// describe the manifest, so the manifest is half of the question.
///
/// `manifest_deps` should already have path dependencies filtered out — those
/// are resolved from disk and never carry a lock entry.  Lock entries come
/// first, in lock order; declared-but-unlocked packages follow in manifest
/// order, so the output is deterministic and reads as "what you had, then what
/// you asked for".
#[must_use]
pub fn update_worklist(
    lock: &[LockedPackage],
    manifest_deps: &[(String, String)],
) -> Vec<UpdateTarget> {
    let mut out: Vec<UpdateTarget> = lock
        .iter()
        .map(|p| UpdateTarget {
            name: p.name.clone(),
            locked: Some(p.version.clone()),
        })
        .collect();
    for (name, _) in manifest_deps {
        if !out.iter().any(|t| &t.name == name) {
            out.push(UpdateTarget {
                name: name.clone(),
                locked: None,
            });
        }
    }
    out
}

/// Read `loft.lock` from `path`.  Returns:
/// - `Ok(Some(lockfile))` on a parse hit.
/// - `Ok(None)` when the file doesn't exist (no lock yet — first run).
/// - `Err(io::Error)` for read errors or unparseable content.
///
/// # Errors
///
/// - IO errors propagate.
/// - `InvalidData` when `schema_version` is missing / unparseable, or
///   when its major version exceeds `SCHEMA_VERSION` (newer file we
///   can't safely consume).
pub fn read_lockfile(path: &Path) -> io::Result<Option<LockFile>> {
    let content = match fs::read_to_string(path) {
        Ok(c) => c,
        Err(e) if e.kind() == io::ErrorKind::NotFound => return Ok(None),
        Err(e) => return Err(e),
    };
    let lock = parse(&content)?;
    Ok(Some(lock))
}

/// Parse `loft.lock` content from a string.  Exposed for tests and for
/// callers that want to validate before writing to disk.
///
/// # Errors
///
/// `InvalidData` on schema-version / structural failures.
pub fn parse(content: &str) -> io::Result<LockFile> {
    let mut lock = LockFile {
        schema_version: 0,
        packages: Vec::new(),
    };
    let mut current: Option<LockedPackage> = None;
    for raw_line in content.lines() {
        let line = raw_line.trim();
        if line.is_empty() || line.starts_with('#') {
            continue;
        }
        if line == "[[package]]" {
            if let Some(pkg) = current.take() {
                lock.packages.push(pkg);
            }
            current = Some(LockedPackage {
                source: "registry".to_string(),
                ..Default::default()
            });
            continue;
        }
        if line.starts_with('[') {
            // Reject unknown top-level tables for now; the format is
            // intentionally narrow.  An older loft seeing a newer
            // table refuses to rewrite the file.
            return Err(io::Error::new(
                io::ErrorKind::InvalidData,
                format!("unknown section `{line}` in loft.lock"),
            ));
        }
        let Some((key, value)) = line.split_once('=') else {
            continue;
        };
        let key = key.trim();
        let value = value.trim();
        if let Some(ref mut pkg) = current {
            match key {
                "name" => pkg.name = unquote(value).to_string(),
                "version" => pkg.version = unquote(value).to_string(),
                "url" => pkg.url = unquote(value).to_string(),
                "sha256" => pkg.sha256 = unquote(value).to_string(),
                "source" => pkg.source = unquote(value).to_string(),
                "deps" => pkg.deps = parse_string_array(value),
                _ => {
                    // Unknown key inside [[package]] — preserve quietly
                    // (forward-compat).  An older loft re-emitting the
                    // file will lose the field, which is acceptable
                    // because `loft install` re-resolves and rewrites
                    // the whole lockfile anyway.
                }
            }
        } else if key == "schema_version" {
            lock.schema_version = unquote(value).parse::<u32>().map_err(|e| {
                io::Error::new(
                    io::ErrorKind::InvalidData,
                    format!("invalid schema_version `{value}`: {e}"),
                )
            })?;
        }
    }
    if let Some(pkg) = current.take() {
        lock.packages.push(pkg);
    }

    if lock.schema_version == 0 {
        return Err(io::Error::new(
            io::ErrorKind::InvalidData,
            "loft.lock missing required `schema_version` field",
        ));
    }
    if lock.schema_version > SCHEMA_VERSION {
        return Err(io::Error::new(
            io::ErrorKind::InvalidData,
            format!(
                "loft.lock schema_version {} is newer than this loft binary supports (max {}); \
                 upgrade loft to read this lockfile",
                lock.schema_version, SCHEMA_VERSION,
            ),
        ));
    }
    Ok(lock)
}

/// Strip surrounding `"..."` quotes from a TOML string value.  Returns
/// the original slice when not quoted (forgiving — the writer always
/// quotes, but a hand-edited lockfile or future format extension might
/// not).
fn unquote(s: &str) -> &str {
    if s.len() >= 2 && s.starts_with('"') && s.ends_with('"') {
        &s[1..s.len() - 1]
    } else {
        s
    }
}

/// Parse a TOML inline string array `["a", "b", ...]`.  Returns an
/// empty Vec for `[]` or malformed input.
fn parse_string_array(s: &str) -> Vec<String> {
    let s = s.trim();
    if !s.starts_with('[') || !s.ends_with(']') {
        return Vec::new();
    }
    let inner = &s[1..s.len() - 1];
    inner
        .split(',')
        .map(str::trim)
        .filter(|p| !p.is_empty())
        .map(|p| unquote(p).to_string())
        .collect()
}

/// Atomic write: serialise `lock` to a scratch file beside `path`, then
/// rename it to `path`.  Avoids leaving a half-written lockfile if the process
/// dies mid-write (which would brick subsequent `loft` invocations
/// against this project).
///
/// # Errors
///
/// IO errors propagate.  Mismatched parent permissions surface as
/// `PermissionDenied`; missing parent dir as `NotFound`.
pub fn write_lockfile(path: &Path, lock: &LockFile) -> io::Result<()> {
    // The scratch name carries the pid and a counter: two installs writing one lockfile at
    // once shared `loft.lock.tmp`, and the first rename took the second writer's file away
    // (`registry_index::replace_atomically` is the same idiom, loft#1045).
    static SEQ: std::sync::atomic::AtomicU64 = std::sync::atomic::AtomicU64::new(0);
    let n = SEQ.fetch_add(1, std::sync::atomic::Ordering::Relaxed);
    let serialised = serialise(lock);
    let tmp_path = path.with_extension(format!("lock.tmp{}-{n}", std::process::id()));
    fs::write(&tmp_path, serialised.as_bytes())?;
    fs::rename(&tmp_path, path).inspect_err(|_| {
        let _ = fs::remove_file(&tmp_path);
    })
}

/// Render the lockfile as a TOML string.  Output is deterministic:
/// packages emit in their declared order; lines are LF-terminated; no
/// trailing whitespace.  Two lockfiles with identical content produce
/// byte-identical output.
#[must_use]
pub fn serialise(lock: &LockFile) -> String {
    use std::fmt::Write as _;
    let mut out = String::new();
    out.push_str("# Auto-generated by loft — do not edit by hand.\n");
    out.push_str("# Run `loft install` to update.\n");
    let _ = writeln!(out, "schema_version = {}", lock.schema_version);
    for pkg in &lock.packages {
        out.push_str("\n[[package]]\n");
        let _ = writeln!(out, "name = {}", quote(&pkg.name));
        let _ = writeln!(out, "version = {}", quote(&pkg.version));
        let _ = writeln!(out, "url = {}", quote(&pkg.url));
        let _ = writeln!(out, "sha256 = {}", quote(&pkg.sha256));
        let _ = writeln!(out, "source = {}", quote(&pkg.source));
        if !pkg.deps.is_empty() {
            let _ = writeln!(out, "deps = {}", string_array(&pkg.deps));
        }
    }
    out
}

fn quote(s: &str) -> String {
    // Lockfile values are constrained (URLs, semver, hex hashes,
    // package names, source kinds) — none contain `"` or `\`.  A
    // bare wrap is safe; if we ever emit values that could contain
    // escapable characters, add backslash escaping here.
    debug_assert!(!s.contains('"'), "lockfile value contains `\"`: {s:?}");
    debug_assert!(!s.contains('\\'), "lockfile value contains `\\`: {s:?}");
    format!("\"{s}\"")
}

fn string_array(items: &[String]) -> String {
    let mut out = String::from("[");
    for (i, item) in items.iter().enumerate() {
        if i > 0 {
            out.push_str(", ");
        }
        out.push_str(&quote(item));
    }
    out.push(']');
    out
}

#[cfg(test)]
mod tests {
    use super::*;
    use std::env;
    use std::path::PathBuf;

    fn tmpdir(name: &str) -> PathBuf {
        let mut p = env::temp_dir();
        p.push(format!("loft_lock_test_{}_{}", std::process::id(), name));
        if p.exists() {
            let _ = fs::remove_dir_all(&p);
        }
        fs::create_dir_all(&p).unwrap();
        p
    }

    fn sample_lock() -> LockFile {
        LockFile {
            schema_version: 1,
            packages: vec![
                LockedPackage {
                    name: "crypto".to_string(),
                    version: "0.1.0".to_string(),
                    url: "https://github.com/loft-lang/loft-crypto/releases/download/v0.1.0/crypto-0.1.0.tar.gz".to_string(),
                    sha256: "abc123def456".to_string(),
                    source: "registry".to_string(),
                    deps: vec![],
                },
                LockedPackage {
                    name: "web".to_string(),
                    version: "0.1.0".to_string(),
                    url: "https://github.com/loft-lang/loft-web/releases/download/v0.1.0/web-0.1.0.tar.gz".to_string(),
                    sha256: "789xyz".to_string(),
                    source: "registry".to_string(),
                    deps: vec!["crypto".to_string()],
                },
            ],
        }
    }

    #[test]
    fn serialise_roundtrip() {
        let lock = sample_lock();
        let serialised = serialise(&lock);
        let parsed = parse(&serialised).expect("parse");
        assert_eq!(parsed, lock, "round-trip mismatch");
    }

    #[test]
    fn serialise_is_deterministic() {
        let lock = sample_lock();
        let a = serialise(&lock);
        let b = serialise(&lock);
        assert_eq!(a, b);
    }

    #[test]
    fn write_atomic_creates_no_tmp() {
        let dir = tmpdir("write_atomic_creates_no_tmp");
        let path = dir.join("loft.lock");
        write_lockfile(&path, &sample_lock()).expect("write");
        assert!(path.exists(), "lockfile not created");
        assert!(!dir.join("loft.lock.tmp").exists(), ".tmp leaked");
        let _ = fs::remove_dir_all(&dir);
    }

    #[test]
    fn write_then_read() {
        let dir = tmpdir("write_then_read");
        let path = dir.join("loft.lock");
        let lock = sample_lock();
        write_lockfile(&path, &lock).expect("write");
        let read = read_lockfile(&path).expect("read").expect("Some");
        assert_eq!(read, lock);
        let _ = fs::remove_dir_all(&dir);
    }

    #[test]
    fn read_missing_returns_none() {
        let dir = tmpdir("read_missing_returns_none");
        let result = read_lockfile(&dir.join("does_not_exist.lock")).expect("no io error");
        assert!(result.is_none());
        let _ = fs::remove_dir_all(&dir);
    }

    #[test]
    fn rejects_newer_schema_version() {
        let content = "schema_version = 999\n\n[[package]]\nname = \"x\"\nversion = \"0.1.0\"\nurl = \"u\"\nsha256 = \"s\"\nsource = \"registry\"\n";
        let err = parse(content).expect_err("should reject newer schema");
        assert_eq!(err.kind(), io::ErrorKind::InvalidData);
        assert!(
            err.to_string()
                .contains("newer than this loft binary supports"),
            "msg: {err}"
        );
    }

    #[test]
    fn rejects_missing_schema_version() {
        let content =
            "[[package]]\nname = \"x\"\nversion = \"0.1.0\"\nurl = \"u\"\nsha256 = \"s\"\n";
        let err = parse(content).expect_err("should reject missing schema");
        assert_eq!(err.kind(), io::ErrorKind::InvalidData);
    }

    #[test]
    fn empty_lockfile_with_only_schema_parses() {
        let content = "schema_version = 1\n";
        let lock = parse(content).expect("parse");
        assert_eq!(lock.schema_version, 1);
        assert!(lock.packages.is_empty());
    }

    #[test]
    fn defaults_source_to_registry_when_missing() {
        let content = "schema_version = 1\n\n[[package]]\nname = \"x\"\nversion = \"0.1.0\"\nurl = \"u\"\nsha256 = \"s\"\n";
        let lock = parse(content).expect("parse");
        assert_eq!(lock.packages[0].source, "registry");
    }

    #[test]
    fn parses_string_array_deps() {
        let content = "schema_version = 1\n\n[[package]]\nname = \"x\"\nversion = \"0.1.0\"\nurl = \"u\"\nsha256 = \"s\"\nsource = \"registry\"\ndeps = [\"a\", \"b\", \"c\"]\n";
        let lock = parse(content).expect("parse");
        assert_eq!(lock.packages[0].deps, vec!["a", "b", "c"]);
    }

    #[test]
    fn comments_and_blank_lines_ignored() {
        let content = r#"# top comment
# another comment
schema_version = 1

# package comment
[[package]]
name = "x"
version = "0.1.0"
url = "u"
sha256 = "s"
source = "registry"
"#;
        let lock = parse(content).expect("parse");
        assert_eq!(lock.packages.len(), 1);
        assert_eq!(lock.packages[0].name, "x");
    }

    // ── loft#830 — the work list is the manifest ∪ the lock ──────────────
    //
    // `loft update` resolved the lock's entries and nothing else, so a
    // dependency added to `loft.toml` was never looked up, never written, and
    // — because the summary counted lock entries — reported as
    // `all N packages up-to-date`.  These cells pin the decision itself: a
    // declared package with no lock entry MUST appear, carrying `locked: None`
    // so the caller can tell "add this" from "consider upgrading this".

    fn deps(pairs: &[(&str, &str)]) -> Vec<(String, String)> {
        pairs
            .iter()
            .map(|(k, v)| ((*k).to_string(), (*v).to_string()))
            .collect()
    }

    #[test]
    fn worklist_includes_declared_package_missing_from_the_lock() {
        let lock = sample_lock();
        let declared = deps(&[("crypto", ">=0.1"), ("hex_grid", ">=0.1")]);
        let work = update_worklist(&lock.packages, &declared);
        let names: Vec<&str> = work.iter().map(|w| w.name.as_str()).collect();
        assert_eq!(
            names,
            vec!["crypto", "web", "hex_grid"],
            "lock entries first, then declarations the lock does not name"
        );
        assert_eq!(work[0].locked.as_deref(), Some("0.1.0"), "crypto is locked");
        assert_eq!(
            work[2].locked, None,
            "hex_grid is declared but unlocked — the case that was skipped"
        );
    }

    #[test]
    fn worklist_does_not_duplicate_a_declared_package_already_locked() {
        let lock = sample_lock();
        let work = update_worklist(&lock.packages, &deps(&[("web", ">=0.1")]));
        assert_eq!(
            work.len(),
            2,
            "web is declared AND locked — one entry: {work:?}"
        );
        assert!(work.iter().all(|w| w.locked.is_some()));
    }

    #[test]
    fn worklist_keeps_transitive_lock_entries_with_no_declaration() {
        // `crypto` is only in the lock (pulled in by `web`).  It must still be
        // resolved — this is the behaviour that existed before #830 and the fix
        // extends it rather than replacing it.
        let lock = sample_lock();
        let work = update_worklist(&lock.packages, &deps(&[]));
        assert_eq!(work.len(), 2);
        assert!(work.iter().all(|w| w.locked.is_some()));
    }

    #[test]
    fn worklist_from_an_empty_lock_is_the_whole_manifest() {
        // A project with no lockfile yet: `loft update` has to build one, so
        // every declared package is work.
        let work = update_worklist(&[], &deps(&[("a", "*"), ("b", ">=2")]));
        assert_eq!(work.len(), 2);
        assert!(work.iter().all(|w| w.locked.is_none()));
    }
}
